using System;

namespace GameDBServer.Server
{
	
	public enum TCPGameServerCmds
	{
		
		CMD_UNKNOWN,
		
		CMD_LOGIN_ON1,
		
		CMD_LOGIN_ON2 = 20,
		
		CMD_NTF_CMD_BASE_ID,
		
		CMD_LOG_OUT,
		
		CMD_SPR_CLIENTHEART,
		
		CMD_SPR_GENERATE_NEW_KEY,
		
		CMD_PREREMOVE_ROLE = 98,
		
		CMD_UNREMOVE_ROLE,
		
		CMD_LOGIN_ON,
		
		CMD_ROLE_LIST,
		
		CMD_CREATE_ROLE,
		
		CMD_REMOVE_ROLE,
		
		CMD_INIT_GAME,
		
		CMD_SYNC_TIME,
		
		CMD_PLAY_GAME,
		
		CMD_SPR_MOVE,
		
		CMD_SPR_MOVEEND,
		
		CMD_SPR_MOVE2,
		
		CMD_OTHER_ROLE,
		
		CMD_OTHER_ROLE_DATA,
		
		CMD_SPR_POSITION,
		
		CMD_SPR_PETPOS,
		
		CMD_SPR_ACTTION,
		
		CMD_SPR_ACTTION2,
		
		CMD_SPR_MAGICCODE,
		
		CMD_SPR_ATTACK,
		
		CMD_SPR_INJURE,
		
		CMD_SPR_REALIVE,
		
		CMD_SPR_RELIFE,
		
		CMD_SPR_CLICKON,
		
		CMD_SYSTEM_MONSTER,
		
		CMD_SPR_MAPCHANGE,
		
		CMD_LOG_OUT_Unused_Dont_Del,
		
		CMD_SPR_NEWTASK,
		
		CMD_SPR_GETATTRIB2,
		
		CMD_SPR_LEAVE,
		
		CMD_SPR_NPC_BUY,
		
		CMD_SPR_NPC_SALEOUT,
		
		CMD_SPR_ADD_GOODS,
		
		CMD_SPR_MOD_GOODS,
		
		CMD_SPR_MERGE_GOODS,
		
		CMD_SPR_SPLIT_GOODS,
		
		CMD_SPR_GET_MERGETYPES,
		
		CMD_SPR_GET_MERGEITEMS,
		
		CMD_SPR_GET_MERGENEWGOODS,
		
		CMD_SPR_CHGCODE,
		
		CMD_SPR_MONEYCHANGE,
		
		CMD_SPR_MODTASK,
		
		CMD_SPR_COMPTASK,
		
		CMD_SPR_EXPCHANGE,
		
		CMD_SPR_GETFRIENDS,
		
		CMD_SPR_ADDFRIEND,
		
		CMD_SPR_REMOVEFRIEND,
		
		CMD_SPR_NEWGOODSPACK,
		
		CMD_SPR_DELGOODSPACK,
		
		CMD_SPR_CLICKONGOODSPACK,
		
		CMD_SPR_GETTHING,
		
		CMD_SPR_CHGPKMODE,
		
		CMD_SPR_CHGPKVAL,
		
		CMD_SPR_UPDATENPCSTATE,
		
		CMD_SPR_NPCSTATELIST,
		
		CMD_SPR_GETNEWTASKDATA,
		
		CMD_SPR_ABANDONTASK,
		
		CMD_SPR_HITED,
		
		CMD_SPR_MODKEYS,
		
		CMD_SPR_CHAT,
		
		CMD_SPR_USEGOODS,
		
		CMD_SPR_CHANGEPOS,
		
		CMD_SPR_NOTIFYCHGMAP,
		
		CMD_SPR_FORGE,
		
		CMD_SPR_ENCHANCE,
		
		CMD_SPR_GETOTHERATTRIB,
		
		CMD_SPR_UPDATE_ROLEDATA,
		
		CMD_SPR_REMOVE_COOLDOWN,
		
		CMD_SPR_MALL_BUY,
		
		CMD_SPR_YINLIANG_BUY,
		
		CMD_SPR_USERMONEYCHANGE,
		
		CMD_SPR_USERYINLIANGCHANGE,
		
		CMD_SPR_GOODSEXCHANGE,
		
		CMD_SPR_EXCHANGEDATA,
		
		CMD_SPR_MOVEGOODSDATA,
		
		CMD_SPR_GOODSSTALL,
		
		CMD_SPR_STALLDATA,
		
		CMD_SPR_STALLNAME,
		
		CMD_SPR_TEAM,
		
		CMD_SPR_TEAMDATA,
		
		CMD_SPR_TEAMID,
		
		CMD_SPR_BATTLE,
		
		CMD_SPR_NPCSCRIPT,
		
		CMD_SPR_DEAD,
		
		CMD_SPR_AUTOFIGHT,
		
		CMD_SPR_HORSE,
		
		CMD_SPR_PET,
		
		CMD_SPR_DIANJIANGLIST,
		
		CMD_SPR_DIANJIANGDATA,
		
		CMD_SPR_DJROOMROLESDATA,
		
		CMD_SPR_DIANJIANG,
		
		CMD_SPR_DIANJIANGFIGHT,
		
		CMD_SPR_DIANJIANGPOINT,
		
		CMD_SPR_GETDJPOINTS,
		
		CMD_SPR_UPDATEINTERPOWER,
		
		CMD_SPR_GOTOMAP,
		
		CMD_SPR_NOTIFYMSG,
		
		CMD_SPR_QUERYIDBYNAME,
		
		CMD_ADDHORSE,
		
		CMD_ADDPET,
		
		CMD_GETHORSELIST,
		
		CMD_GETOTHERHORSELIST,
		
		CMD_GETPETLIST,
		
		CMD_MODHORSE,
		
		CMD_MODPET,
		
		CMD_SELECTHORSE,
		
		CMD_GETGOODSLISTBYSITE,
		
		CMD_GETLINEINFO,
		
		CMD_GETJINGMAILIST,
		
		CMD_UP_JINGMAI_LEVEL,
		
		CMD_GETOTHERJINGMAILIST,
		
		CMD_SPR_LOADALREADY,
		
		CMD_SPR_BULLETINMSG,
		
		CMD_SPR_GMAUTH,
		
		CMD_SPR_EQUIPUPGRADE,
		
		CMD_SPR_ENCHASEJEWEL,
		
		CMD_SPR_SHOWBIGUAN,
		
		CMD_SPR_GETBIGUAN,
		
		CMD_SPR_UPSKILLLEVEL,
		
		CMD_SPR_ADD_SKILL,
		
		CMD_SPR_JINGMAI_INFO,
		
		CMD_SPR_HORSEENCHANCE,
		
		CMD_SPR_HORSEUPGRADE,
		
		CMD_SPR_SALEGOODS,
		
		CMD_SPR_SELFSALEGOODSLIST,
		
		CMD_SPR_OTHERSALEGOODSLIST,
		
		CMD_SPR_MARKETROLELIST,
		
		CMD_SPR_MARKETGOODSLIST,
		
		CMD_SPR_MARKETBUYGOODS,
		
		CMD_SPR_MODDEFSKILLID,
		
		CMD_SPR_MODAUTODRINK,
		
		CMD_SPR_PLAYDECO,
		
		CMD_SPR_BUFFERDATA,
		
		CMD_SPR_RUNTOMAP,
		
		CMD_SPR_SEARCHROLES,
		
		CMD_SPR_LISTROLES,
		
		CMD_SPR_LISTTEAMS,
		
		CMD_SPR_RESETBAG,
		
		CMD_SPR_DAILYTASKDATA,
		
		CMD_SPR_DAILYJINGMAIDATA,
		
		CMD_SPR_CHGNUMSKILLID,
		
		CMD_SPR_GETSKILLUSEDNUM,
		
		CMD_SPR_CHGHORSEBODY,
		
		CMD_SPR_PORTABLEBAGDATA,
		
		CMD_SPR_RESETPORTABLEBAG,
		
		CMD_SPR_EXECWABAO,
		
		CMD_SPR_GETWABAODATA,
		
		CMD_SPR_GETHUODONGDATA,
		
		CMD_SPR_GETWLOGINGIFT,
		
		CMD_SPR_GETNEWSTEPGIFT,
		
		CMD_SPR_GETMTIMEGIFT,
		
		CMD_SPR_GETBIGGIFT,
		
		CMD_SPR_GETSONGLIGIFT,
		
		CMD_SPR_CHGHUODONGID,
		
		CMD_SPR_FUBENDATA,
		
		CMD_SPR_ENTERFUBEN,
		
		CMD_SPR_NOTIFYENTERFUBEN,
		
		CMD_SPR_CLIENTHEART_OLD,
		
		CMD_SPR_OHTERJINGMAIEXP,
		
		CMD_GETRANDOMNAME,
		
		CMD_SKILLUSEDNUMFULL,
		
		CMD_SPR_GETFUBENHISTDATA,
		
		CMD_SPR_GETFUBENBEGININFO,
		
		CMD_SPR_COPYMAPMONSTERSNUM,
		
		CMD_SPR_FINDMONSTER,
		
		CMD_SPR_BATCHYINPIAO,
		
		CMD_SPR_FORCETOLAOFANG,
		
		CMD_SPR_CHGPURPLENAME,
		
		CMD_SPR_CHGLIANZHAN,
		
		CMD_SPR_GETROLEDAILYDATA,
		
		CMD_SPR_GETBOSSINFODICT,
		
		CMD_SPR_GETPAIHANGLIST,
		
		CMD_SPR_YABIAODATA,
		
		CMD_SPR_STARTYABIAO,
		
		CMD_SPR_ENDYABIAO,
		
		CMD_SPR_YABIAOTAKEGOODS,
		
		CMD_SPR_TOUBAO,
		
		CMD_SPR_GETOTHERATTRIB2,
		
		CMD_SPR_NEWBIAOCHE,
		
		CMD_SPR_DELBIAOCHE,
		
		CMD_SPR_FINDBIAOCHE,
		
		CMD_SPR_CHGBIAOCHELIFEV,
		
		CMD_SPR_NOTIFYENDCHONGXUE,
		
		CMD_SPR_ADDHORSELUCKY,
		
		CMD_SPR_BATTLEKILLEDNUM,
		
		CMD_SPR_CHGBATTLENAMEINFO,
		
		CMD_SPR_NOFITYPOPUPWIN,
		
		CMD_SPR_NOTIFYBATTLEROLEINFO,
		
		CMD_SPR_NOTIFYBATTLEENDINFO,
		
		CMD_SPR_GETCHONGZHIJIFEN,
		
		CMD_SPR_NOTIFYTEAMCHGLEVEL,
		
		CMD_SPR_GETFUBENHISTLISTDATA,
		
		CMD_SPR_CHGHEROINDEX,
		
		CMD_GETOTHERHORSEDATA,
		
		CMD_UPDATEALLTHINGINDEXS,
		
		CMD_SPR_CHGHALFYINLIANGPERIOD,
		
		CMD_SPR_GETBANGHUILIST,
		
		CMD_SPR_CREATEBANGHUI,
		
		CMD_SPR_CHGBANGHUIINFO,
		
		CMD_SPR_QUERYBANGHUIDETAIL,
		
		CMD_SPR_UPDATEBANGHUIBULLETIN,
		
		CMD_SPR_GETBHMEMBERDATALIST,
		
		CMD_SPR_UPDATEBHVERIFY,
		
		CMD_SPR_APPLYTOBHMEMBER,
		
		CMD_SPR_ADDBHMEMBER,
		
		CMD_SPR_REMOVEBHMEMBER,
		
		CMD_SPR_QUITFROMBANGHUI,
		
		CMD_SPR_DESTROYBANGHUI,
		
		CMD_SPR_BANGHUIVERIFY,
		
		CMD_SPR_INVITETOBANGHUI,
		
		CMD_SPR_CHGBHMEMBERZHIWU,
		
		CMD_SPR_CHGBHMEMBERCHENGHAO,
		
		CMD_SPR_SEARCHROLESFROMDB,
		
		CMD_SPR_AGREETOTOBANGHUI,
		
		CMD_SPR_REFUSEAPPLYTOBH,
		
		CMD_SPR_GETBANGGONGHIST,
		
		CMD_SPR_DONATEBGMONEY,
		
		CMD_SPR_DONATEBGGOODS,
		
		CMD_SPR_BANGGONGCHANGE,
		
		CMD_SPR_GETBANGQIINFO,
		
		CMD_SPR_RENAMEBANGQI,
		
		CMD_SPR_UPLEVELBANGQI,
		
		CMD_SPR_CHGJUNQILIFEV,
		
		CMD_SPR_NEWJUNQI,
		
		CMD_SPR_DELJUNQI,
		
		CMD_SPR_LINGDIFORBH,
		
		CMD_SPR_CHGHUANGDIROLEID,
		
		CMD_SPR_GETBHLINGDIINFODICTBYBHID,
		
		CMD_SPR_SETLINGDITAX,
		
		CMD_SPR_TAKELINGDITAXMONEY,
		
		CMD_SPR_GETHUANGDIBHINFO,
		
		CMD_SPR_NOTIFYBHZHIWU,
		
		CMD_SPR_OPENYANGGONGBK,
		
		CMD_SPR_REFRESHYANGGONGBK,
		
		CMD_SPR_CLICKYANGGONGBK,
		
		CMD_SPR_REFRESHQIZHENGE,
		
		CMD_SPR_QIZHEGEBUY,
		
		CMD_SPR_QUERYQIZHEGEBUYHIST,
		
		CMD_SPR_QUICKJINGMAI,
		
		CMD_SPR_QUICKHORSEENCHANCE,
		
		CMD_SPR_QUICKEQUIPENHANCE,
		
		CMD_SPR_QUICKEQUIPFORGE,
		
		CMD_SPR_GETHUANGDIROLEDATA,
		
		CMD_SPR_ADDHUANGFEI,
		
		CMD_SPR_REMOVEHUANGFEI,
		
		CMD_SPR_GETHUANGFEIDATA,
		
		CMD_SPR_SENDTOLAOFANG,
		
		CMD_SPR_TAKEOUTLAOFANG,
		
		CMD_SPR_BANCHAT,
		
		CMD_SPR_CHGHUANGHOU,
		
		CMD_SPR_GETLINGDIMAPINFO,
		
		CMD_SPR_GETHUANGCHENGMAPINFO,
		
		CMD_SPR_ADDLINGDITAXMONEY,
		
		CMD_SPR_INVITEADDHUANGFEI,
		
		CMD_SPR_AGREEADDHUANGFEI,
		
		CMD_SPR_TASKTRANSPORT,
		
		CMD_SPT_LINGLIGUANZHU,
		
		CMD_SPR_GETGOODSBYDBID,
		
		CMD_SPR_QUICKCOMPLETETASK,
		
		CMD_SPR_QUERYCHONGZHIMONEY,
		
		CMD_SPR_GETFIRSTCHONGZHIDALI,
		
		CMD_SPR_NOTIFYBATTLESIDE,
		
		CMD_SPR_NOTIFYBATTLEAWARD,
		
		CMD_SPR_EXECWABAOBYYAOSHI,
		
		CMD_SPR_SUBFORGE,
		
		CMD_SPR_GETUSERMAILLIST,
		
		CMD_SPR_GETUSERMAILDATA,
		
		CMD_SPR_FETCHMAILGOODS,
		
		CMD_SPR_DELETEUSERMAIL,
		
		CMD_SPR_GETMAILSENDCODE,
		
		CMD_SPR_SENDUSERMAIL,
		
		CMD_SPR_RECEIVELASTMAIL,
		
		CMD_SPR_EQUIPBORNINDEXUPDATE,
		
		CMD_SPR_EQUIPINHERIT,
		
		CMD_SPR_QUERYINPUTFANLI,
		
		CMD_SPR_QUERYINPUTJIASONG,
		
		CMD_SPR_QUERYINPUTKING,
		
		CMD_SPR_QUERYLEVELKING,
		
		CMD_SPR_QUERYEQUIPKING,
		
		CMD_SPR_QUERYHORSEKING,
		
		CMD_SPR_QUERYJINGMAIKING,
		
		CMD_SPR_QUERYAWARDHIST,
		
		CMD_SPR_EXECUTEINPUTFANLI,
		
		CMD_SPR_EXECUTEINPUTJIASONG,
		
		CMD_SPR_EXECUTEINPUTKING,
		
		CMD_SPR_EXECUTELEVELKING,
		
		CMD_SPR_EXECUTEEQUIPKING,
		
		CMD_SPR_EXECUTEHORSEKING,
		
		CMD_SPR_EXECUTEJINGMAIKING,
		
		CMD_SPR_MALLZHENQIBUY,
		
		CMD_SPR_FETCHACTIVITYAWARD,
		
		CMD_SPR_VIPDAILYDATA,
		
		CMD_SPR_USEVIPDAILYPRIORITY,
		
		CMD_SPR_ACTIVITYTRANSPORT,
		
		CMD_SPR_YANGGONGBKDAILYDATA,
		
		CMD_SPR_FETCHYANGGONGBKJIFENAWARD,
		
		CMD_SPR_QUERYSHILIANTAAWARDINFO,
		
		CMD_SPR_FETCHSHILIANTAAWARD,
		
		CMD_SPR_COMPLETETINYCLIENT,
		
		CMD_SPR_USERGOLDCHANGE,
		
		CMD_SPR_NOTIFYSHENGXIAOGUESSSTAT,
		
		CMD_SPR_NOTIFYSHENGXIAOGUESSRESULT,
		
		CMD_SPR_ADDSHENGXIAOMORTGAGE,
		
		CMD_SPR_QUERYROLESHENGXIAOGUESSLIST,
		
		CMD_SPR_QUERYSHENGXIAOGUESSHISTORY,
		
		CMD_SPR_QUERYSHENGXIAORECENTRESULTLIST,
		
		CMD_SPR_QUERYSHENGXIAOGUESSSELFHISTORY,
		
		CMD_SPR_UPDATETENGXUNFCMRATE,
		
		CMD_SPR_NEWNPC,
		
		CMD_SPR_DELNPC,
		
		CMD_SPR_EXTGRIDBYYUANBAO,
		
		CMD_SPR_SUBMONEY,
		
		CMD_SPR_EXTBAGNUMBYYUANBAO,
		
		CMD_SPR_STOPMOVE,
		
		CMD_SPR_NOTIFYEQUIPSTRONG,
		
		CMD_SPR_EXCUTENPCLUATALK,
		
		CMD_SPR_EXCUTENPCLUAFUNCTION,
		
		CMD_SPR_ARENABATTLE,
		
		CMD_SPR_ARENABATTLEKILLEDNUM,
		
		CMD_SPR_CITYWARREQUEST,
		
		CMD_SPR_TAKELINGDIDAILYAWARD,
		
		CMD_SPR_NOTIFYOPENWINDOW,
		
		CMD_SPR_CHENGJIUDATA,
		
		CMD_SPR_FETCHCHENGJIUAWARD,
		
		CMD_SPR_DSHIDECMD,
		
		CMD_SPR_NEWDECO,
		
		CMD_SPR_DELDECO,
		
		CMD_SPR_MENDEQUIPMENT,
		
		CMD_SPR_NOTIFYGOODSINFO,
		
		CMD_SPR_ROLEPARAMSCHANGE,
		
		CMD_SPR_EQUIPFENJIE,
		
		CMD_SPR_JINGYUANEXCHANGE,
		
		CMD_SPR_HUIZHANGEXCHANGE,
		
		CMD_SPR_ACTIVATNEXTLEVELJINGMAI,
		
		CMD_SPR_FETCHVIPONCEAWARD,
		
		CMD_SPR_TASKTRANSPORT2,
		
		CMD_SPR_ACTIVATNEXTLEVELWUXUE,
		
		CMD_SPR_CAIJI,
		
		CMD_SPR_RUNTASKPLOTLUA,
		
		CMD_SPR_PLAYGAMEEFFECT,
		
		CMD_SPR_TRANSFERSOMETHING,
		
		CMD_SPR_CHANGEPETAITYPE,
		
		CMD_SPR_FETCHMALLDATA,
		
		CMD_SPR_MALLQIANGGOUBUYGOODS,
		
		CMD_SPR_FETCHZUANHUANGAWARD,
		
		CMD_SPR_SETSYSTEMOPENPARAMS,
		
		CMD_SPR_ENTERTASKFUBEN,
		
		CMD_SPR_GETUPLEVELGIFTOK,
		
		CMD_SPR_UPDATEWEIGHTS,
		
		CMD_SPR_GETTASKAWARDS,
		
		CMD_SPR_NOTIFYGETGOODSPACK,
		
		CMD_SPR_RESETJINDANBAG,
		
		CMD_SPR_GETJINDANGOODSLIST,
		
		CMD_SPR_ZAJINDAN,
		
		CMD_SPR_QUERYZAJINDANHISTORY,
		
		CMD_SPR_QUERYSELFZAJINDANHISTORY,
		
		CMD_SPR_GETWANGCHENGMAPINFO,
		
		CMD_SPR_GETLIMITTIMELOGINGIFT,
		
		CMD_SPR_ROLESTATUSCMD,
		
		CMD_SPR_GETTO60AWARD,
		
		CMD_SPR_GETKAIFUONLINEINFO,
		
		CMD_SPR_GETDAYCHONGZHIDALI,
		
		CMD_SPR_GETJIERIXMLDATA,
		
		CMD_SPR_QUERYJIERIDALIBAO,
		
		CMD_SPR_QUERYJIERIDENGLU,
		
		CMD_SPR_QUERYJIERIVIP,
		
		CMD_SPR_QUERYJIERICZSONG,
		
		CMD_SPR_QUERYJIERICZLEIJI,
		
		CMD_SPR_QUERYJIERIZIKA,
		
		CMD_SPR_QUERYJIERIXIAOFEIKING,
		
		CMD_SPR_QUERYJIERICZKING,
		
		CMD_SPR_EXECUTEJIERIDALIBAO,
		
		CMD_SPR_EXECUTEJIERIDENGLU,
		
		CMD_SPR_EXECUTEJIERIVIP,
		
		CMD_SPR_EXECUTEJIERICZSONG,
		
		CMD_SPR_EXECUTEJIERICZLEIJI,
		
		CMD_SPR_EXECUTEJIERIZIKA,
		
		CMD_SPR_EXECUTEJIERIXIAOFEIKING,
		
		CMD_SPR_EXECUTEJIERICZKING,
		
		CMD_SPR_CHGJIERICHENGHAO,
		
		CMD_SPR_FACTIVITIESDATA,
		
		CMD_SPR_YUANBAOCOMPLETETASK,
		
		CMD_SPR_QUERYHEFUDALIBAO,
		
		CMD_SPR_QUERYHEFUVIP,
		
		CMD_SPR_QUERYHEFUCZSONG,
		
		CMD_SPR_QUERYHEFUFANLI,
		
		CMD_SPR_QUERYHEFUPKKING,
		
		CMD_SPR_QUERYHEFUWCKING,
		
		CMD_SPR_QUERYXINFANLI,
		
		CMD_SPR_EXECUHEFUDALIBAO,
		
		CMD_SPR_EXECUHEFUVIP,
		
		CMD_SPR_EXECUHEFUCZSONG,
		
		CMD_SPR_EXECUHEFUFANLI,
		
		CMD_SPR_EXECUHEFUPKKING,
		
		CMD_SPR_EXECUHEFUWCKING,
		
		CMD_SPR_EXECUXINFANLI,
		
		CMD_SPR_ONEKEYQUICKSALEOUT,
		
		CMD_SPR_ACTIVATNEXTLEVELZHANHUN,
		
		CMD_SPR_ACTIVATNEXTLEVELRONGYU,
		
		CMD_SPR_ACTIVATRONGYUBUFFER,
		
		CMD_SPR_LIANLUJINGLIAN,
		
		CMD_SPR_ZJDJIFEN,
		
		CMD_SPR_FETCHZJDJIFENAWARD,
		
		CMD_SPR_QUERYACTIVITYINFO,
		
		CMD_SPR_XINGYUNCHOUJIANG,
		
		CMD_SPR_QUERYYUEDUCHOUJIANGHISTORY,
		
		CMD_SPR_QUERYSELFQUERYYUEDUCHOUJIANGHISTORY,
		
		CMD_SPR_EXECUTEYUEDUCHOUJIANG,
		
		CMD_SPR_QUERYYUEDUCHOUJIANGINFO,
		
		CMD_SPR_EXECUTEHUNQIEXCHANGE,
		
		CMD_SPR_EXECUTECHANGEOCCUPATION,
		
		CMD_SPR_EXECUTECHANGELIFE,
		
		CMD_SPR_BEGINBLINK,
		
		CMD_SPR_ENDBLINK,
		
		CMD_SPR_GETROLEUSINGGOODSDATALIST,
		
		CMD_SPR_EXECUTEPROPADDPOINT,
		
		CMD_SPR_EXECUTERECOMMENDPROPADDPOINT,
		
		CMD_SPR_EXECUTERECLEANPROPADDPOINT,
		
		CMD_SPR_QUERYCLEANPROPADDPOINT,
		
		CMD_SPR_BLOODCASTLEBEGINFIGHT,
		
		CMD_SPR_BLOODCASTLEKILLMONSTERAHASDONE,
		
		CMD_SPR_BLOODCASTLEENDFIGHT,
		
		CMD_SPR_FUBENCLEANOUT,
		
		CMD_SPR_FUBENPASSNOTIFY,
		
		CMD_SPR_QUERYFUBENINFO,
		
		CMD_SPR_ATTACK2,
		
		CMD_SPR_COMPLETEFLASHSCENE,
		
		CMD_SPR_FRESHPLAYERSCENEKILLMONSTERAHASDONE,
		
		CMD_SPR_REFURBISHTASKSTARLEVEL,
		
		CMD_SPR_COMPLETEDAILYCIRCLETASKFORONCECLICK,
		
		CMD_SPR_ADMIREDPLAYER,
		
		CMD_SPR_QUERYBLOODCASTLEINFO,
		
		CMD_SPR_EQUIPAPPENDPROP,
		
		CMD_SPR_BLOODCASTLEPREPAREFIGHT,
		
		CMD_SPR_BLOODCASTLECOMBATPOINT,
		
		CMD_SPR_BLOODCASTLEKILLMONSTERSTATUS,
		
		CMD_SPR_QUERYCAMPBATTLEINFO,
		
		CMD_SPR_QUERYDAIMONSQUAREINFO,
		
		CMD_SPR_QUERYDAIMONSQUARETIMERINFO,
		
		CMD_SPR_QUERYDAIMONSQUAREMONSTERWAVEANDPOINTRINFO,
		
		CMD_SPR_DAIMONSQUAREENDFIGHT,
		
		CMD_SPR_UPDATEEVERYDAYONLINEAWARDGIFTINFO,
		
		CMD_SPR_GETEVERYDAYONLINEAWARDGIFT,
		
		CMD_SPR_UPDATEEVERYDAYSERIESLOGININFO,
		
		CMD_SPR_GETEVERYDAYSERIESLOGINAWARDGIFT,
		
		CMD_SPR_FRESHPLAYERSCENEOVERTIME,
		
		CMD_SPR_UPDATEGETTHINGSFLAG,
		
		CMD_SPR_BLOODCASTLEPLAYERNUMNOTIFY,
		
		CMD_SPR_DAIMONSQUAREPLAYERNUMNOTIFY,
		
		CMD_SPR_BATTLEPLAYERNUMNOTIFY,
		
		CMD_SPR_EXCHANGEMOJINGANDQIFU,
		
		CMD_SPR_GETMEDITATEEXP,
		
		CMD_SPR_GETMEDITATETIMEINFO,
		
		CMD_SPR_QUERYTOTALLOGININFO,
		
		CMD_SPR_GETTOTALLOGINAWARD,
		
		CMD_SPR_CHANGELIFEFOREQUIP,
		
		CMD_SPR_FLAKEOFFCHANGELIFEFOREQUIP,
		
		CMD_SPR_ONEKEYFINDFRIEND,
		
		CMD_SPR_ONEKEYADDFRIEND,
		
		CMD_SPR_GETVIPAWARD,
		
		CMD_SPR_DAILYACTIVEDATA,
		
		CMD_SPR_GETDAILYACTIVEAWARD,
		
		CMD_SPR_SETAUTOASSIGNPROPERTYPOINT,
		
		CMD_SPR_GETBLOODCASTLEAWARD,
		
		CMD_SPR_GETDAIMONSQUAREAWARD,
		
		CMD_SPR_GETCOPYMAPAWARD,
		
		CMD_SPR_GETSKILLINFO,
		
		CMD_SPR_EXPERIENCECOPYMAPINFO,
		
		CMD_SPR_ZHANMENGSHIJIAN_DETAIL,
		
		CMD_SPR_KAIFUACTIVITYINFO,
		
		CMD_SPR_GETTHEKINGOFPKINFO,
		
		CMD_SPR_NOTIFYTHEKINGOFPKAWARDINFO,
		
		CMD_SPR_ANGELTEMPLETIMERINFO,
		
		CMD_SPR_ANGELTEMPLEFIGHTEND,
		
		CMD_SPR_ANGELTEMPLEFIGHTINFOALL,
		
		CMD_SPR_ANGELTEMPLEFIGHTINFOSINGLE,
		
		CMD_SPR_ANGELTEMPLESPARK,
		
		CMD_SPR_GETANGELTEMPLEBASEINFO,
		
		CMD_SPR_QUERYADRATIONPKKINGINFO,
		
		CMD_SPR_ADRATIONPKKING,
		
		CMD_SPR_JINGJI_DETAIL,
		
		CMD_SPR_JINGJI_REQUEST_CHALLENGE,
		
		CMD_SPR_JINGJI_CHALLENGE_END,
		
		CMD_SPR_JINGJI_NOTIFY_START,
		
		CMD_SPR_JINGJI_CHALLENGEINFO,
		
		CMD_SPR_JINGJI_RANKING_REWARD,
		
		CMD_SPR_JINGJICHANG_REMOVE_CD,
		
		CMD_SPR_JINGJICHANG_GET_BUFF,
		
		CMD_SPR_JINGJICHANG_JUNXIAN_LEVELUP,
		
		CMD_SPR_JINGJICHANG_LEAVE,
		
		CMD_SPR_CHGFAKEROLELIFEV,
		
		CMD_SPR_NEWFAKEROLE,
		
		CMD_SPR_DELFAKEROLE,
		
		CMD_SPR_OPENMARKET,
		
		CMD_SPR_MARKETSALEMONEY,
		
		CMD_SPR_GETVIPINFO,
		
		CMD_SPR_GETVIPLEVELAWARD,
		
		CMD_SPR_VIPLEVELUP,
		
		CMD_SPR_GETLIXIANBAITANTICKS,
		
		CMD_SPR_UPDATELIXIANBAITANTICKS,
		
		CMD_SPR_QUERYOPENGRIDTICK,
		
		CMD_SPR_QUERYOPENPORTABLEGRIDTICK,
		
		CMD_SPR_STARTMEDITATE,
		
		CMD_SPR_ZHANMENGBUILDUPLEVEL,
		
		CMD_SPR_ZHANMENGBUILDGETBUFFER,
		
		CMD_SPR_GETBAITANLOG,
		
		CMD_SPR_GETPUSHMESSAGEINFO,
		
		CMD_SPR_ACTIVATIONPICTUREJUDGE,
		
		CMD_SPR_GETNPICTUREJUDGEINFO,
		
		CMD_SPR_MUEQUIPUPGRADE,
		
		CMD_SPR_WINGUPSTAR,
		
		CMD_SPR_WINGUPGRADE,
		
		CMD_SPR_WINGOFFON,
		
		CMD_SPR_CHECK,
		
		CMD_SPR_REFERPICTUREJUDGE,
		
		CMD_SPR_GETMOJINGEXCHANGEINFO,
		
		CMD_SPR_REFRESH_ICON_STATE,
		
		CMD_SPR_EQUIPAPPENDINHERIT,
		
		CMD_SPR_SWEEP_WANMOTA,
		
		CMD_SPR_UPDATE_SWEEP_STATE,
		
		CMD_SPR_GET_WANMOTA_DETAIL,
		
		CMD_SPR_GET_SWEEP_REWARD,
		
		CMD_SPR_LISTCOPYTEAMS,
		
		CMD_SPR_COPYTEAM,
		
		CMD_SPR_COPYTEAMDATA,
		
		CMD_SPR_COPYTEAMSTATE,
		
		CMD_SPR_REGEVENTNOTIFY,
		
		CMD_SPR_LISTCOPYTEAMDATA,
		
		CMD_SPR_COPYTEAMDAMAGEINFO,
		
		CMD_SPR_GOLDCOPYSCENEPREPAREFIGHT,
		
		CMD_SPR_GOLDCOPYSCENEMONSTERWAVE,
		
		CMD_SPR_GETNEWZONEACTIVEAWARD,
		
		CMD_SPR_QUERYUPLEVELMADMAN,
		
		CMD_SPR_QUERYNEWZONEACTIVE,
		
		CMD_SPR_QUERYUPLEVELGIFTINFO,
		
		CMD_SPR_GETUPLEVELGIFTAWARD,
		
		CMD_SPR_JINGJI_START_FIGHT,
		
		CMD_SPR_QUERY_REPAYACTIVEINFO,
		
		CMD_SPR_GET_REPAYACTIVEAWARD,
		
		CMD_SPR_QUERY_ALLREPAYACTIVEINFO,
		
		CMD_SPR_QUERYACTIVITYSOMEINFO,
		
		CMD_SPR_PLAYBOSSANIMATION,
		
		CMD_SPR_ENDBOSSANIMATION,
		
		CMD_SPR_QUERY_TODAYCANDOINFO,
		
		CMD_SPR_QUERY_GETOLDRESINFO,
		
		CMD_SPR_GET_OLDRESOURCE,
		
		CMD_SPR_EXTENSIONPROPSHITED,
		
		CMD_SPR_EXEC_WASHPROPS,
		
		CMD_SPR_EXEC_WASHPROPSINHERIT,
		
		CMD_SPR_BATTLE_SCORE_LIST,
		
		CMD_SPR_STORYCOPYMAPINFO,
		
		CMD_SPR_GETUSERMAILCOUNT,
		
		CMD_SPR_QUERYIMPETRATEINFO,
		
		CMD_SPR_EXECUTEIMPETRATE,
		
		CMD_SPR_OPENMARKET2,
		
		CMD_SPR_MARKETSALEMONEY2,
		
		CMD_SPR_SALEGOODS2,
		
		CMD_SPR_SELFSALEGOODSLIST2,
		
		CMD_SPR_OTHERSALEGOODSLIST2,
		
		CMD_SPR_MARKETROLELIST2,
		
		CMD_SPR_MARKETGOODSLIST2,
		
		CMD_SPR_MARKETBUYGOODS2,
		
		CMD_SPR_QUERYSTARCONSTELLATIONINFO,
		
		CMD_SPR_EXECUTEACTIVATIONSTARCONSTELLATION,
		
		CMD_SPR_CHANGEANGLE,
		
		CMD_SPR_UPDATESHARESTATE,
		
		CMD_SPR_GETSHAREAWARD,
		
		CMD_SPR_GETSHARESTATE,
		
		CMD_SPR_BROADSPECIALHINTTEXT,
		
		CMD_SPR_MAPAIEVENT,
		
		CMD_SPR_EXEC_LIANZHI,
		
		CMD_SPR_QUERY_LIANZHICOUNT,
		
		CMD_SPR_UPGRADE_CHENGJIU,
		
		CMD_SPR_GETFIRSTCHARGEINFO,
		
		CMD_SPR_BATCHFETCHMAILGOODS,
		
		CMD_SPR_PUSH_VERSION,
		
		CMD_SPR_NOTIFYTEAMCHGZHANLI,
		
		CMD_SPR_NOTIFYSELFCHGZHANLI,
		
		CMD_SPR_NOTIFYOTHERBUFFERDATA,
		
		CMD_SPR_NOTIFYSHOWGONGGAO,
		
		CMD_SPR_GETWINGINFO,
		
		CMD_SPR_EMOLAIXIMONSTERINFO,
		
		CMD_SPR_CAIJI_START,
		
		CMD_SPR_CAIJI_FINISH,
		
		CMD_SPR_CAIJI_LASTNUM,
		
		CMD_SPR_QUERYJIERITOTALCONSUME,
		
		CMD_SPR_EXECUTEJIERITOTALCONSUME,
		
		CMD_MAP_TELEPORT,
		
		CMD_SPR_SPECIALMACHINE,
		
		CMD_SPR_EXTRADATA,
		
		CMD_SPR_SHOWALLICON,
		
		CMD_SPR_USEGOODS_RESULT,
		
		CMD_SPR_SCOREBOX,
		
		CMD_SPR_CDTIME,
		
		CMD_SPR_QUERY_SPEC_PLAT_FULI,
		
		CMD_SPR_EXCUTE_SPEC_PLAT_FULI,
		
		CMD_SPR_FAST_CACHE,
		
		CMD_SPR_GE = 699,
		
		CMD_SPR_CHENGZHAN_JINGJIA,
		
		CMD_SPR_GET_CHENGZHAN_DAILY_AWARD,
		
		CMD_SPR_LUOLANCHENGZHAN,
		
		CMD_SPR_LUOLANCHENGZHAN_LONGTA_ROLEINFO,
		
		CMD_SPR_LUOLANCHENGZHAN_QIZHI_OWNERINFO,
		
		CMD_SPR_LUOLANCHENGZHAN_LONGTA_OWNERINFO,
		
		CMD_SPR_GET_LUOLANCHENGZHU_INFO,
		
		CMD_SPR_LUOLANCHENGZHAN_RESULT_INFO,
		
		CMD_SPR_GET_LUOLANCHENGZHAN_REQUEST_INFO_LIST,
		
		CMD_SPR_SERVERUPDATE_ZHANMENGZIJIN,
		
		CMD_SPR_MODIFY_FASHION,
		
		CMD_SPR_GETBANGHUIFUBEN,
		
		CMD_SPR_GETBANGHUIFUBENAWARD,
		
		CMD_SPR_GET_ELEMENTHRT_SLIST = 720,
		
		CMD_SPR_GET_ELEMENTHRTS_INFO,
		
		CMD_SPR_USE_ELEMENTHRT,
		
		CMD_SPR_GET_SOMEELEMENTHRTS,
		
		CMD_SPR_POWER_ELEMENTHRT,
		
		CMD_SPR_RESET_EHRTSBAG,
		
		CMD_SPR_GET_USINGELEMENTHRT_SLIST,
		
		CMD_SPR_HOLD_QINGGONGYAN = 730,
		
		CMD_SPR_GET_QINGGONGYAN,
		
		CMD_SPR_JOIN_QINGGONGYAN,
		
		CMD_SPR_IFQINGGONGYANOPEN,
		
		CMD_SPR_GETDAMONGOODSLIST = 740,
		
		CMD_SPR_GET_PET_LIST = 750,
		
		CMD_SPR_GET_PET_INFO,
		
		CMD_SPR_CALL_PET,
		
		CMD_SPR_MOVE_PET,
		
		CMD_SPR_RESET_PETBAG,
		
		CMD_SPR_FAZHEN_BOSS = 760,
		
		CMD_SPR_GET_STORE_YINLIANG,
		
		CMD_SPR_GET_STORE_MONEY,
		
		CMD_SPR_STORE_YINLIANG_CHANGE,
		
		CMD_SPR_STORE_MONEY_CHANGE,
		
		CMD_SPR_JIERIACT_STATE = 770,
		
		CMD_SPR_ACHIEVEMENT_RUNE_INFO = 780,
		
		CMD_SPR_ACHIEVEMENT_RUNE_UP,
		
		CMD_SPR_PRESTIGE_MEDAL_INFO,
		
		CMD_SPR_PRESTIGE_MEDAL_UP,
		
		CMD_SPR_ARTIFACT_UP = 791,
		
		CMD_SPR_GET_LINGYU_LIST = 800,
		
		CMD_SPR_ADVANCE_LINGYU_LEVEL,
		
		CMD_SPR_ADVANCE_LINGYU_SUIT,
		
		CMD_SPR_WING_ZHULING = 810,
		
		CMD_SPR_WING_ZHUHUN,
		
		CMD_SPR_HYSY_LIANSHA = 818,
		
		CMD_SPR_HYSY_STOP_LIANSHA,
		
		CMD_SPR_HYSY_ENQUEUE,
		
		CMD_SPR_HYSY_DEQUEUE,
		
		CMD_SPR_HYSY_QUEUE_PLAYER_NUM,
		
		CMD_SPR_HYSY_ENTER_NOTIFY,
		
		CMD_SPR_HYSY_ENTER_RESPOND,
		
		CMD_SPR_HYSY_AWARD,
		
		CMD_SPR_HYSY_SCORE_INFO,
		
		CMD_SPR_NOTIFY_TIME_STATE,
		
		CMD_SPR_HYSY_SUCCESS_COUNT,
		
		CMD_SPR_HYSY_ADD_SCORE,
		
		CMD_SPR_REGION_EVENT,
		
		CMD_SYNC_TIME_BY_CLIENT,
		
		CMD_SYNC_TIME_BY_SERVER,
		
		CMD_SYNC_CHANGE_DAY_SERVER,
		
		CMD_SPR_GETLUOLANCHENGZHU = 840,
		
		CMD_SPR_QUERYADRATIONLANCHENGZHUO,
		
		CMD_SPR_ADRATIONLANCHENGZHU,
		
		CMD_SPR_GET_YUEKA_DATA = 850,
		
		CMD_SPR_GET_YUEKA_AWARD,
		
		CMD_SECOND_PASSWORD_CHECK_STATE = 860,
		
		CMD_SECOND_PASSWORD_SET,
		
		CMD_SECOND_PASSWORD_VERIFY,
		
		CMD_SECOND_PASSWORD_CANCEL,
		
		CMD_SPR_MARRY_FUBEN = 870,
		
		CMD_SPR_MARRY_ROSE,
		
		CMD_SPR_MARRY_RING,
		
		CMD_SPR_MARRY_MESSAGE,
		
		CMD_SPR_MARRY_PARTY_QUERY = 880,
		
		CMD_SPR_MARRY_PARTY_CREATE,
		
		CMD_SPR_MARRY_PARTY_CANCEL,
		
		CMD_SPR_MARRY_PARTY_JOIN,
		
		CMD_SPR_MARRY_PARTY_JOIN_LIST,
		
		CMD_SPR_MARRY_INIT = 890,
		
		CMD_SPR_MARRY_REPLY,
		
		CMD_SPR_MARRY_DIVORCE,
		
		CMD_SPR_MARRY_AUTO_REJECT,
		
		CMD_SPR_MARRY_NOTIFY,
		
		CMD_SPR_MARRY_UPDATE,
		
		CMD_SPR_MARRY_SPOUSE_DATA,
		
		CMD_SPR_THEME_GETXMLDATA = 905,
		
		CMD_SPR_THEME_ZHIGOU_QUERY,
		
		CMD_SPR_THEME_DUIHUAN_QUERY,
		
		CMD_SPR_THEME_LIBAO_QUERY,
		
		CMD_SPR_THEME_LIBAO_EXECUTE,
		
		CMD_SPR_QUERY_JIERI_GIVE_INFO = 920,
		
		CMD_SPR_JIERI_GIVE_TO_OTHER,
		
		CMD_SPR_GET_JIERI_GIVE_AWARD,
		
		CMD_SPR_QUERY_JIERI_GIVE_KING_INFO,
		
		CMD_SPR_GET_JIERI_GIVE_KING_AWARD,
		
		CMD_SPR_QUERY_JIERI_RECV_KING_INFO,
		
		CMD_SPR_GET_JIERI_RECV_KING_AWARD,
		
		CMD_DB_EXECUXJIERIFANLI,
		
		CMD_SPR_QUERY_GUARD_POINT_RECOVER = 930,
		
		CMD_SPR_GUARD_POINT_RECOVER,
		
		CMD_SPR_QUERY_GUARD_STATUE_INFO,
		
		CMD_SPR_GUARD_STATUE_LEVEL_UP,
		
		CMD_SPR_GUARD_STATUE_SUIT_UP,
		
		CMD_SPR_MOD_GUARD_SOUL_EQUIP,
		
		CMD_SPR_QUERY_LIANXU_CHARGE_INFO = 940,
		
		CMD_SPR_GET_LIANXU_CHARGE_AWARD,
		
		CMD_SPR_QUERY_JIERI_RECV_INFO = 944,
		
		CMD_SPR_GET_JIERI_RECV_AWARD,
		
		CMD_SPR_GET_FASHION_SLIST,
		
		CMD_SPR_QUERY_DANBICHONGZHI_INFO,
		
		CMD_SPR_GET_DANBICHONGZHI_AWARD,
		
		CMD_SPR_TIANTI_JOIN = 950,
		
		CMD_SPR_TIANTI_QUIT,
		
		CMD_SPR_TIANTI_ENTER,
		
		CMD_SPR_TIANTI_AWARD,
		
		CMD_SPR_TIANTI_DAY_DATA,
		
		CMD_SPR_TIANTI_MONTH_PAIHANG,
		
		CMD_SPR_TIANTI_GET_PAIMING_AWARDS,
		
		CMD_SPR_ROLE_ATTRIBUTE_VALUE = 968,
		
		CMD_SPR_TIANTI_GET_LOG,
		
		CMD_SPR_EFFECT_HIDE_FLAGS,
		
		CMD_SPR_LOGIN_WAITING_INFO,
		
		CMD_SPR_MERLIN_QUERY = 981,
		
		CMD_SPR_MERLIN_STAR_UP,
		
		CMD_SPR_MERLIN_LEVEL_UP,
		
		CMD_SPR_MERLIN_SECRET_ATTR_UPDATE,
		
		CMD_SPR_MERLIN_SECRET_ATTR_REPLACE,
		
		CMD_SPR_MERLIN_SECRET_ATTR_NOT_REPLACE,
		
		CMD_SPR_FLUORESCENT_GEM_RESET_BAG = 991,
		
		CMD_SPR_FLUORESCENT_GEM_EQUIP,
		
		CMD_SPR_FLUORESCENT_GEM_UN_EQUIP,
		
		CMD_SPR_FLUORESCENT_GEM_LEVEL_UP,
		
		CMD_SPR_FLUORESCENT_GEM_DIG,
		
		CMD_SPR_FLUORESCENT_GEM_RESOLVE,
		
		CMD_SPR_FLUORESCENT_GEM_EQUIP_CHANGES,
		
		CMD_SPR_TALENT_GET_DATA = 1000,
		
		CMD_SPR_TALENT_ADD_EXP,
		
		CMD_SPR_TALENT_WASH,
		
		CMD_SPR_TALENT_ADD_EFFECT,
		
		CMD_SPR_WARN_INFO,
		
		CMD_SPR_ELEMENT_WAR_JOIN = 1010,
		
		CMD_SPR_ELEMENT_WAR_QUIT,
		
		CMD_SPR_ELEMENT_WAR_ENTER,
		
		CMD_SPR_ELEMENT_WAR_PLAYER_NUM,
		
		CMD_SPR_ELEMENT_WAR_CANCEL = 1016,
		
		CMD_SPR_ELEMENT_WAR_SCORE_INFO = 1014,
		
		CMD_SPR_ELEMENT_WAR_AWARD,
		
		CMD_SPR_SPREAD_SIGN = 1017,
		
		CMD_SPR_SPREAD_AWARD,
		
		CMD_SPR_SPREAD_VERIFY_CODE,
		
		CMD_SPR_SPREAD_TEL_CODE_GET,
		
		CMD_SPR_SPREAD_TEL_CODE_VERIFY,
		
		CMD_SPR_SPREAD_INFO,
		
		CMD_SPR_COPY_WOLF_SCORE_INFO = 1025,
		
		CMD_SPR_COPY_WOLF_AWARD,
		
		CMD_SPR_TODAY_DATA = 1030,
		
		CMD_SPR_TODAY_AWARD,
		
		CMD_SPR_FUND_INFO,
		
		CMD_SPR_FUND_BUY,
		
		CMD_SPR_FUND_AWARD,
		
		CMD_SPR_UNION_PALACE_DATA,
		
		CMD_SPR_UNION_PALACE_UP,
		
		CMD_SPR_PET_SKILL_UP,
		
		CMD_SPR_PET_SKILL_AWAKE,
		
		CMD_SPR_PET_SKILL_AWAKE_COST,
		
		CMD_SPR_ACTIVATE_INFO,
		
		CMD_SPR_ACTIVATE_AWARD,
		
		CMD_SPR_YONGZHEZHANCHANG_JOIN = 1100,
		
		CMD_SPR_YONGZHEZHANCHANG_ENTER,
		
		CMD_SPR_YONGZHEZHANCHANG_AWARD,
		
		CMD_SPR_YONGZHEZHANCHANG_STATE,
		
		CMD_SPR_YONGZHEZHANCHANG_SIDE_SCORE,
		
		CMD_SPR_YONGZHEZHANCHANG_SELF_SCORE,
		
		CMD_SPR_YONGZHEZHANCHANG_LIANSHA,
		
		CMD_SPR_YONGZHEZHANCHANG_STOP_LIANSHA,
		
		CMD_SPR_YONGZHEZHANCHANG_AWARD_GET,
		
		CMD_SPR_GVOICE_SCENE_DATA = 1110,
		
		CMD_SPR_GVOICE_SET_PRIORITYS,
		
		CMD_SPR_GVOICE_GET_PRIORITYS,
		
		CMD_SPR_KUAFU_BOSS_JOIN = 1120,
		
		CMD_SPR_KUAFU_BOSS_ENTER,
		
		CMD_SPR_KUAFU_BOSS_DATA,
		
		CMD_SPR_KUAFU_BOSS_STATE,
		
		CMD_SPR_KUAFU_MAP_INFO = 1140,
		
		CMD_SPR_KUAFU_MAP_ENTER,
		
		CMD_SPR_LANGHUNLINGYU_LONGTA_ROLEINFO = 1150,
		
		CMD_SPR_LANGHUNLINGYU_QIZHI_OWNERINFO,
		
		CMD_SPR_LANGHUNLINGYU_LONGTA_OWNERINFO,
		
		CMD_SPR_LANGHUNLINGYU_JOIN,
		
		CMD_SPR_LANGHUNLINGYU_DATA,
		
		CMD_SPR_LANGHUNLINGYU_CITY_DATA,
		
		CMD_SPR_LANGHUNLINGYU_WORLD_DATA,
		
		CMD_SPR_LANGHUNLINGYU_ENTER,
		
		CMD_SPR_LANGHUNLINGYU_GET_DAY_AWARD,
		
		CMD_SPR_LANGHUNLINGYU_AWARD,
		
		CMD_SPR_LANGHUNLINGYU_ADMIRE_DATA,
		
		CMD_SPR_LANGHUNLINGYU_ADMIRE_HIST,
		
		CMD_SPR_LANGHUNLINGYU_ADMIRE,
		
		CMD_SPR_HOLYITEM_DATA = 1200,
		
		CMD_SPR_HOLYITEM_PART_DATA,
		
		DB_Juntuan_Change_Member_ZhiWu = 1240,
		
		CMD_SPR_QUERY_JIERI_PLAT_CHARGE_KING = 1300,
		
		CMD_SPR_MORI_JOIN,
		
		CMD_SPR_MORI_QUIT,
		
		CMD_MORI_NTF_ROLE_COUNT,
		
		CMD_MORI_NTF_ENTER,
		
		CMD_NTF_MORI_MONSTER_EVENT,
		
		CMD_NTF_MORI_COPY_CANCEL,
		
		CMD_SPR_SEVEN_DAY_ACT_QUERY = 1310,
		
		CMD_SPR_SEVEN_DAY_ACT_GET_AWARD,
		
		CMD_SPR_SEVEN_DAY_ACT_QIANG_GOU,
		
		CMD_NTF_BANGHUI_CHANGE_NAME = 1315,
		
		CMD_SPR_SOUL_STONE_QUERY_GET = 1320,
		
		CMD_SPR_SOUL_STONE_GET,
		
		CMD_SPR_SOUL_STONE_LVL_UP,
		
		CMD_SPR_SOUL_STONE_MOD_EQUIP,
		
		CMD_SPR_SOUL_STONE_RESET_BAG,
		
		CMD_SPR_SET_FUNCTION_OPEN = 1330,
		
		CMD_SPR_JINGJICHANG_GET_ROLE_LOOKS = 1340,
		
		CMD_SPR_PKKING_GET_ROLE_LOOKS,
		
		CMD_SPR_LUOLANKING_GET_ROLE_LOOKS,
		
		CMD_SPR_ZHENGBA_GET_MAIN_INFO = 1350,
		
		CMD_SPR_ZHENGBA_GET_ALL_PK_LOG,
		
		CMD_SPR_ZHENGBA_GET_ALL_PK_STATE,
		
		CMD_SPR_ZHENGBA_GET_16_PK_STATE,
		
		CMD_SPR_ZHENGBA_SUPPORT,
		
		CMD_SPR_ZHENGBA_YA_ZHU,
		
		CMD_NTF_ZHENGBA_CAN_ENTER,
		
		CMD_SPR_ZHENGBA_ENTER,
		
		CMD_NTF_ZHENGBA_PK_RESULT,
		
		CMD_SPR_ZHENGBA_GET_MINI_STATE,
		
		CMD_SPR_ZHENGBA_QUERY_JOIN_HINT,
		
		CMD_COUPLE_ARENA_GET_MAIN_DATA = 1370,
		
		CMD_COUPLE_ARENA_GET_ZHAN_BAO,
		
		CMD_COUPLE_ARENA_GET_PAI_HANG,
		
		CMD_COUPLE_ARENA_SET_READY,
		
		CMD_COUPLE_ARENA_SINGLE_JOIN,
		
		CMD_COUPLE_ARENA_QUIT,
		
		CMD_COUPLE_ARENA_NTF_CAN_ENTER,
		
		CMD_COUPLE_ARENA_ENTER,
		
		CMD_COUPLE_ARENA_NTF_PK_RESULT,
		
		CMD_COUPLE_ARENA_NTF_COUPLE_STATE,
		
		CMD_COUPLE_ARENA_REG_STATE_WATCHER,
		
		CMD_COUPLE_ARENA_NTF_BUFF_HOLDER,
		
		CMD_COUPLE_ARENA_DB_SAVE_ZHAN_BAO,
		
		CMD_COUPLE_ARENA_DB_CLR_ZHAN_BAO,
		
		CMD_ID_PLACE_HOLDER_BY_CHENJG_END = 1399,
		
		CMD_SPR_QUERY_OTHER_SALE_PRICE,
		
		CMD_OCCUPATION_PURCHASE = 1410,
		
		CMD_OCCUPATION_CHANGE,
		
		CMD_OCCUPATION_CREATE_SUMMONER,
		
		CMD_SPR_FAHONGBAO = 1420,
		
		CMD_SPR_HONGBAORANK,
		
		CMD_SPR_MYHONGBAO,
		
		CMD_SPR_SHOWHONGBAO,
		
		CMD_SPR_HONGBAODEATILS,
		
		CMD_SPR_ZHANMENGHONGBAODTIPS,
		
		CMD_SPR_SYSTEMHONGBAOTIPS,
		
		CMD_SPR_GET_JIERIHONGBAOBANG_AWARDS = 1428,
		
		CMD_SPR_QUERY_JIERIHONGBAOBANG_DATA,
		
		CMD_DB_GET_ZHANMENGRANKLIST,
		
		CMD_DB_GET_JIRRIRECVRANKLIST,
		
		CMD_DB_UPDATE_ZHANMENGHONGBAO,
		
		CMD_DB_RECV_ZHANMENGHONGBAO,
		
		CMD_DB_GET_ZHANMENGHONGBAOLIST,
		
		CMD_DB_UPDATE_JIERIHONGBAO,
		
		CMD_DB_RECV_JIERIHONGBAO,
		
		CMD_DB_GET_JIERIHONGBAOLIST,
		
		CMD_DB_GET_ZHANMENGHONGBAOLOGLIST,
		
		CMD_DB_GET_ZHANMENGHONGBAORECVLIST,
		
		CMD_DB_GET_JIERIHONGBAOCOUNT,
		
		CMD_DB_EXECUTE_HUIJIHUTI = 1445,
		
		CMD_DB_HUIJI_LEVEL_STAR_UP,
		
		CMD_DB_ARMOR_LEVEL_STAR_UP,
		
		CMD_DB_EXECUTE_BIANSHEN,
		
		CMD_DB_BIANSHEN_LEVEL_UP,
		
		CMD_SPR_JINGLINGYUANSUJUEXING_ACTIVE,
		
		CMD_SPR_JINGLINGYUANSUJUEXING_UPGRADE,
		
		CMD_DB_UPDATEJUEXING_JLYS_DATA,
		
		CMD_SPR_GETINPUT_POINTS_EXCHGINFO = 1500,
		
		CMD_SPR_GETWEEKEND_INPUT_DATA,
		
		CMD_SPR_SYNCINPUT_POINTS_ONLY,
		
		CMD_SPR_SPECIALACTIVITY_GETXMLDATA = 1510,
		
		CMD_SPR_SPECIALACTIVITY_QUERY,
		
		CMD_SPR_SPECIALACTIVITY_FETCHAWARD,
		
		CMD_SPR_BUILD_GET_LIST = 1550,
		
		CMD_SPR_BUILD_EXCUTE,
		
		CMD_SPR_BUILD_FINISH,
		
		CMD_SPR_BUILD_REFRESH,
		
		CMD_SPR_BUILD_GET_ALLLEVEL_AWARD,
		
		CMD_SPR_BUILD_GET_AWARD,
		
		CMD_SPR_BUILD_OPEN_QUEUE,
		
		CMD_SPR_BUILD_GET_QUEUE,
		
		CMD_SPR_BUILD_GET_STATE,
		
		CMD_SPR_BUILD_GET_ALLLEVEL_AWARD_STATE,
		
		CMD_SPR_BUILD_SYNC_SINGLE,
		
		CMD_SPR_ONEPIECE_GET_INFO = 1600,
		
		CMD_SPR_ONEPIECE_ROLL,
		
		CMD_SPR_ONEPIECE_TRIGGER_EVENT,
		
		CMD_SPR_ONEPIECE_SYNC_EVENT,
		
		CMD_SPR_ONEPIECE_MOVE,
		
		CMD_SPR_ONEPIECE_ROLL_MIRACLE,
		
		CMD_SPR_ONEPIECE_DICE_BUY,
		
		CMD_SPR_ONEPIECE_SYNC_DICE,
		
		CMD_SPR_VIDEO_OPEN = 1700,
		
		CMD_SPR_QUERYJIERIMEIRILEIJI = 1806,
		
		CMD_SPR_EXECUTEJIERIMEIRILEIJI,
		
		CMD_SPR_JIERI_MEIRI_PLAT_CHARGE_KING_QUERY,
		
		CMD_SPR_JIERI_MEIRI_PLAT_CHARGE_KING_EXECUTE,
		
		CMD_SPR_ZHANYONG_LINYL = 1999,
		
		CMD_SPR_GET_FUMOMONEY_ACCEPTNUM = 2020,
		
		CMD_SPR_UPDATA_FUMOMONEY_ACCEPTNUM,
		
		CMD_SPR_GIVE_FUMOMONEY,
		
		CMD_SPR_GET_FUMOMAIL_LIST,
		
		CMD_SPR_FUMOATTR_APPEND,
		
		CMD_SPR_FUMOATTR,
		
		CMD_SPR_SAVE_FUMOATTR,
		
		CMD_SPR_TODAY_USER_GIVE_LIST,
		
		CMD_SPR_NOT_SAVE_FUMOATTR,
		
		CMD_SPR_UPDATA_FUMOMAIL_ISREAD,
		
		CMD_SPR_REBORN_YINJI_LEVELUP,
		
		CMD_SPR_REBORN_YINJI_GETINFO,
		
		CMD_SPR_REBORN_YINJI_RESET,
		
		CMD_SPR_REBORN_YINJI_CHOOSE,
		
		CMD_SPR_REBORN_BAG_GETINFO = 2040,
		
		CMD_SPR_REBORN_BAG_RESET,
		
		CMD_SPR_REBORN_STORE_RESET,
		
		CMD_SPR_REBORN_OPENGRIDTICK,
		
		CMD_SPR_REBORN_OPENBAGTICK,
		
		CMD_SPR_REBORN_BAGDATA_NOTIFY,
		
		CMD_SPR_REBORN_SALEONE,
		
		CMD_SPR_REBORN_SALEMORE,
		
		CMD_SPR_REBORN_EXTGRID,
		
		CMD_SPR_REBORN_BAGNUM,
		
		CMD_SPR_REBORN_DAKONG,
		
		CMD_SPR_REBORN_SHOW,
		
		CMD_SPR_REBORN_SHOWDATA_NOTIFY,
		
		CMD_SPR_REBORN_UPDATA,
		
		CMD_SPR_REBORN_INLAY,
		
		CMD_SPR_REBORN_DEMOUNT,
		
		CMD_SPR_REBORN_STONECOMPLEX,
		
		CMD_SPR_REBORN_XUANCAICOMPLEX,
		
		CMD_SPR_REBORN_STONERESOLVE,
		
		CMD_SPR_REBORN_SHOWMODEL,
		
		CMD_SPR_REBORN_BATCH_STONERESOLVE,
		
		CMD_SPR_REBORN_SHOWMODEL_NOTIFY,
		
		CMD_SPR_REGRESSACTIVE_GETFILE = 2070,
		
		CMD_SPR_REGRESSACTIVE_GETSIGNINFO,
		
		CMD_SPR_REGRESSACTIVE_SING,
		
		CMD_SPR_REGRESSACTIVE_GETSTOREINFO,
		
		CMD_SPR_REGRESSACTIVE_STOREBUY,
		
		CMD_SPR_REGRESSACTIVE_INPUTINFO,
		
		CMD_SPR_REGRESSACTIVE_INPUT,
		
		CMD_SPR_REGRESSACTIVE_ZHIGOU_QUERY,
		
		CMD_SPR_GET_GOLDAUCTION = 2080,
		
		CMD_SPR_SET_GOLDAUCTION,
		
		CMD_SPR_SET_BOCAI,
		
		CMD_SPR_GET_BOCAI,
		
		CMD_SPR_UPDATE_BOCAI,
		
		CMD_SPR_BOCAI_SHOP_GET,
		
		CMD_SPR_BOCAI_SHOP_BUY,
		
		CMD_SPR_BOCAI_EXCHANGE,
		
		CMD_SPR_HOLYSTAMP_UPGRADE = 2090,
		
		CMD_SPR_HOLYSTAMP_INLAY,
		
		CMD_SPR_HOLYSTAMP_DEMOUNT,
		
		CMD_SPR_HOLYSTAMP_BAGRESET,
		
		CMD_SPR_HORSE_RESET,
		
		CMD_SPR_REBORNHOLE_PERFUSION,
		
		CMD_SPR_REBORNHOLE_ABSCHRECKEN,
		
		CMD_SPR_MAZINGERSTORE_UPGRADE,
		
		CMD_SPR_PROCESSAREAEVENT = 3000,
		
		CMD_SPR_NOTIFYMSGWITHGOODS,
		
		CMD_SPR_GET_MEDITATE_GOODS,
		
		CMD_UPDATE_GOODSLIMIT,
		
		CMD_DB_GET_ROLE_BASEINFO,
		
		CMD_DB_KF5V5_ADD_ITEM_LOG = 3670,
		
		CMD_SPR_SPR_GET_KF5V5_INFO = 3680,
		
		CMD_SPR_KF5V5_CREATE_ZHANDUI = 3685,
		
		CMD_SPR_KF5V5_DELETE_MEMBER,
		
		CMD_SPR_KF5V5_INVITE_TO_ZHANDUI,
		
		CMD_SPR_KF5V5_GETZHANDUI_LIST,
		
		CMD_SPR_KF5V5_NOTIFY_ZHANDUI_INVITE,
		
		CMD_SPR_KF5V5_AGREE_ZHANDUI_INVITE,
		
		CMD_SPR_KF5V5_UPDATE_ZHANDUI_XUYAN,
		
		CMD_SPR_KF5V5_ROLE_SIGN,
		
		CMD_SPR_KF5V5_ROLE_CANCLE_SIGN,
		
		CMD_SPR_KF5V5_GET_FRIENDS_LSIT,
		
		CMD_SPR_KF5V5_GET_MY_ZHANDUI_INFO,
		
		CMD_SPR_KF5V5_NOTIFY_PIPEI_SUCCESS,
		
		CMD_SPR_KF5V5_ENTER_KF5V5_SCENE,
		
		CMD_SPR_KF5V5_CHANGE_ZHANDUI_LEADER,
		
		CMD_SPR_KF5V5_JIESAN_ZHANDUI,
		
		CMD_SPR_KF5V5_QUERY_JINGJI_DATA,
		
		CMD_SPR_KF5V5_NOTIFY_SCENINFO = 3708,
		
		CMD_SPR_KF5V5_GET_LOG_LIST,
		
		CMD_SPR_KF5V5_BATTLE_RESULT,
		
		CMD_SPR_KF5V5_QUIT_ZHANDUI,
		
		CMD_SPR_KF5V5_SIGNUP_STATE,
		
		CMD_SPR_KF5V5_CONFIRM_BATTLE,
		
		CMD_SPR_KF5V5_ACCEPT_CONFIRM_BATTLE,
		
		CMD_SPR_KF5V5_LOAD_ZHANDUI_DATA,
		
		CMD_SPR_KF5V5_UPDATE_ZHANDUI_DATA,
		
		CMD_SPR_KF5V5_UPDATE_ROLE_ZHANDUI_AND_ZHIWU,
		
		CMD_SPR_KF5V5_Notify_ZHANDUI_DATA_CHANGED,
		
		CMD_SPR_KF5V5_UPDATE_ZHANDUI_DATA_ZORK = 3722,
		
		CMD_SPR_KF5V5_UPDATE_ZHANDUI_DATA_ESCAPE,
		
		CMD_DB_START_CMD = 10000,
		
		CMD_DB_UPDATE_POS,
		
		CMD_DB_UPDATE_EXPLEVEL,
		
		CMD_DB_UPDATE_INTERPOWER,
		
		CMD_DB_UPDATEMONEY1_CMD,
		
		CMD_DB_ADDGOODS_CMD,
		
		CMD_DB_UPDATEGOODS_CMD,
		
		CMD_DB_UPDATETASK_CMD,
		
		CMD_DB_UPDATEPKMODE_CMD,
		
		CMD_DB_UPDATEPKVAL_CMD,
		
		CMD_DB_UPDATEKEYS,
		
		CMD_DB_UPDATEUSERMONEY_CMD,
		
		CMD_DB_UPDATEUSERYINLIANG_CMD,
		
		CMD_DB_MOVEGOODS_CMD,
		
		CMD_DB_UPDATE_LEFTFIGHTSECS,
		
		CMD_DB_ROLE_ONLINE,
		
		CMD_DB_ROLE_HEART,
		
		CMD_DB_ROLE_OFFLINE,
		
		CMD_DB_GET_CHATMSGLIST,
		
		CMD_DB_HORSEON,
		
		CMD_DB_HORSEOFF,
		
		CMD_DB_PETOUT,
		
		CMD_DB_PETIN,
		
		CMD_DB_ADDDJPOINT,
		
		CMD_DB_UPJINGMAI_LEVEL,
		
		CMD_DB_REGUSERID,
		
		CMD_DB_BANROLENAME,
		
		CMD_DB_BANROLECHAT,
		
		CMD_DB_GETBANROLECATDICT,
		
		CMD_DB_ADDBULLMSG,
		
		CMD_DB_REMOVEBULLMSG,
		
		CMD_DB_GETBULLMSGDICT,
		
		CMD_DB_UPDATEONLINETIME,
		
		CMD_DB_GAMECONFIGDICT,
		
		CMD_DB_GAMECONIFGITEM,
		
		CMD_DB_RESETBIGUAN,
		
		CMD_DB_ADDSKILL,
		
		CMD_DB_UPSKILLINFO,
		
		CMD_DB_UPDATEJINGMAIEXP,
		
		CMD_DB_UPDATEDEFSKILLID,
		
		CMD_DB_UPDATEAUTODRINK,
		
		CMD_DB_UPDATEDAILYTASKDATA,
		
		CMD_DB_UPDATEDAILYJINGMAI,
		
		CMD_DB_UPDATENUMSKILLID,
		
		CMD_DB_UPDATEPBINFO,
		
		CMD_DB_UPDATHUODONGINFO,
		
		CMD_DB_SUBCHONGZHIJIFEN,
		
		CMD_DB_USELIPINMA,
		
		CMD_DB_UPDATEFUBENDATA,
		
		CMD_DB_GETFUBENSEQID,
		
		CMD_DB_UPDATEROLEDAILYDATA,
		
		CMD_DB_UPDATEBUFFERITEM,
		
		CMD_DB_UNDELROLENAME,
		
		CMD_DB_ADDFUBENHISTDATA,
		
		CMD_DB_UPDATELIANZHAN,
		
		CMD_DB_UPDATEKILLBOSS,
		
		CMD_DB_UPDATEROLESTAT,
		
		CMD_DB_UPDATEYABIAODATA,
		
		CMD_DB_UPDATEYABIAODATASTATE,
		
		CMD_DB_UPDATEBATTLENAME,
		
		CMD_DB_ADDMALLBUYITEM,
		
		CMD_DB_GETLIPINMAINFO,
		
		CMD_DB_UPDATECZTASKID,
		
		CMD_DB_GETTOTALONLINENUM,
		
		CMD_DB_UPDATEBATTLENUM,
		
		CMD_DB_UPDATEHEROINDEX,
		
		CMD_DB_FORCERELOADPAIHANG,
		
		CMD_DB_ADDYINPIAOBUYITEM,
		
		CMD_DB_DELROLENAME,
		
		CMD_SPR_QUERYUMBYNAME,
		
		CMD_DB_QUERYBHMGRLIST,
		
		CMD_DB_UPDATEBANGGONG_CMD,
		
		CMD_DB_UPDATEBHTONGQIAN_CMD,
		
		CMD_DB_GETBHJUNQILIST,
		
		CMD_DB_GETBHLINGDIDICT,
		
		CMD_DB_UPDATELINGDIFORBH,
		
		CMD_DB_GETLEADERROLEIDBYBHID,
		
		CMD_DB_ADDBHTONGQIAN_CMD,
		
		CMD_DB_ADDQIZHENGEBUYITEM,
		
		CMD_DB_UPDATEJIEBIAOINFO,
		
		CMD_DB_ADDREFRESHQIZHENREC,
		
		CMD_DB_CLEARCACHINGROLEIDATA,
		
		CMD_DB_ADDMONEYWARNING,
		
		CMD_DB_QUERYCHONGZHIMONEY,
		
		CMD_DB_ADDYINLIANGBUYITEM,
		
		CMD_DB_ADDBANGGONGBUYITEM,
		
		CMD_DB_SENDUSERMAIL,
		
		CMD_DB_GETUSERMAILDATA,
		
		CMD_DB_FINDROLEID_BYROLENAME,
		
		CMD_DB_QUERYLIMITGOODSUSEDNUM,
		
		CMD_DB_UPDATELIMITGOODSUSEDNUM,
		
		CMD_DB_UPDATEDAILYVIPDATA,
		
		CMD_DB_UPDATEDAILYYANGGONGBKJIFENDATA,
		
		CMD_DB_UPDATESINGLETIMEAWARDFLAG,
		
		CMD_DB_ADDSHENGXIAOGUESSHIST,
		
		CMD_DB_UPDATEUSERGOLD_CMD,
		
		CMD_DB_ADDGOLDBUYITEM,
		
		CMD_DB_UPDATEROLEBAGNUM,
		
		CMD_DB_SETLINGDIWARREQUEST,
		
		CMD_DB_UPDATEGOODSLIMIT,
		
		CMD_DB_UPDATEROLEPARAM,
		
		CMD_DB_ADDQIANGGOUBUYITEM,
		
		CMD_DB_ADDQIANGGOUITEM,
		
		CMD_DB_QUERYCURRENTQIANGGOUITEM,
		
		CMD_DB_QUERYQIANGGOUBUYITEMS,
		
		CMD_DB_UPDATEQIANGGOUTIMEOVER,
		
		CMD_DB_GETBANGHUIMINIDATA,
		
		CMD_DB_ADDBUYITEMFROMNPC,
		
		CMD_DB_ADDZAJINDANHISTORY,
		
		CMD_DB_QUERYQIANGGOUBUYITEMINFO,
		
		CMD_DB_QUERYFIRSTCHONGZHIBYUSERID,
		
		CMD_DB_QUERYKAIFUONLINEAWARDROLEID,
		
		CMD_DB_ADDKAIFUONLINEAWARD,
		
		CMD_DB_ADDGIVEUSERMONEYITEM,
		
		CMD_DB_QUERYKAIFUONLINEAWARDLIST,
		
		CMD_DB_ADDEXCHANGE1ITEM,
		
		CMD_DB_ADDEXCHANGE2ITEM,
		
		CMD_DB_ADDEXCHANGE3ITEM,
		
		CMD_DB_ADDFALLGOODSITEM,
		
		CMD_DB_UPDATEROLEPROPS,
		
		CMD_DB_QUERYTODAYCHONGZHIMONEY,
		
		CMD_DB_QUERYDAYCHONGZHIBYUSERID,
		
		CMD_DB_CLEARALLCACHINGROLEDATA,
		
		CMD_DB_QUERYXINGYUNORYUEDUCHOUJIANGINFO,
		
		CMD_DB_EXECUXINGYUNORYUEDUCHOUJIANGINFO,
		
		CMD_DB_ADDYUEDUCHOUJIANGHISTORY,
		
		CMD_DB_EXECUTECHANGEOCCUPATION,
		
		CMD_DB_QUERYBLOODCASTLEENTERCOUNT,
		
		CMD_DB_UPDATEBLOODCASTLEENTERCOUNT,
		
		CMD_DB_QUERYFUBENHISINFO,
		
		CMD_DB_CLEANDATAWHENFRESHPLAYERLOGOUT,
		
		CMD_DB_FINISHFRESHPLAYERSTATUS,
		
		CMD_DB_EXECUTECHANGETASKSTARLEVEL,
		
		CMD_DB_EXECUTEUPDATEROLESOMEINFO,
		
		CMD_DB_QUERYDAYACTIVITYTOTALPOINT,
		
		CMD_DB_QUERYDAYACTIVITYSELFPOINT,
		
		CMD_DB_UPDATEDAYACTIVITYSELFPOINT,
		
		CMD_DB_QUERYEVERYDAYONLINEAWARDGIFTINFO,
		
		CMD_DB_ADD_ZHANMENGSHIJIAN,
		
		CMD_DB_ZHANMENGSHIJIAN_DETAIL,
		
		CMD_DB_JINGJICHANG_GET_DATA,
		
		CMD_DB_JINGJICHANG_GET_CHALLENGE_DATA,
		
		CMD_DB_JINGJICHANG_CREATE_DATA,
		
		CMD_DB_JINGJICHANG_REQUEST_CHALLENGE,
		
		CMD_DB_JINGJICHANG_CHALLENGE_END,
		
		CMD_DB_JINGJICHANG_SAVE_DATA,
		
		CMD_DB_JINGJICHANG_ZHANBAO_DATA,
		
		CMD_DB_JINGJICHANG_REMOVE_CD,
		
		CMD_DB_JINGJICHANG_GET_RANKING_AND_NEXTREWARDTIME,
		
		CMD_DB_JINGJICHANG_UPDATE_NEXTREWARDTIME,
		
		CMD_DB_ADD_BAITANLOG,
		
		CMD_DB_UPDATEPUSHMESSAGEINFO,
		
		CMD_DB_QUERYPUSHMESSAGEUSERLIST,
		
		CMD_DB_ADDWING,
		
		CMD_DB_MODWING,
		
		CMD_DB_REFERPICTUREJUDGE,
		
		CMD_DB_QUERYMOJINGEXCHANGEINFO,
		
		CMD_DB_UPDATEMOJINGEXCHANGEINFO,
		
		CMD_DB_MODIFY_WANMOTA,
		
		CMD_DB_GET_WANMOTA_DETAIL,
		
		CMD_DB_QUERY_REPAYACTIVEINFO,
		
		CMD_DB_GET_REPAYACTIVEAWARD,
		
		CMD_DB_UPDATE_ACCOUNT_ACTIVE,
		
		CMD_DB_QUERY_GETOLDRESINFO,
		
		CMD_DB_UPDATE_OLDRESOURCE,
		
		CMD_DB_UPDATEGOODS_CMD2,
		
		CMD_DB_UPDATESTARCONSTELLATION,
		
		CMD_DB_SAVECONSUMELOG,
		
		CMD_DB_QUERYVIPLEVELAWARDFLAG,
		
		CMD_DB_UPDATEVIPLEVELAWARDFLAG,
		
		CMD_DB_UPDATEFIRSTCHARGE,
		
		CMD_DB_FIRSTCHARGE_CONFIG,
		
		CMD_DB_UPDATEBANGHUIFUBEN,
		
		CMD_DB_ADD_STORE_YINLIANG,
		
		CMD_DB_ADD_STORE_MONEY,
		
		CMD_DB_GM_UPDATE_BANGLEVEL,
		
		CMD_DB_UPDATE_LINGYU,
		
		CMD_DB_REQUESTNEWGMAILLIST,
		
		CMD_DB_MODIFYROLEGMAIL,
		
		CMD_DB_QUERYROLEMONEYINFO,
		
		CMD_DB_ALL_COMPLETION_OF_TASK_BY_TASKID,
		
		CMD_DB_ROLE_BUY_YUE_KA_BUT_OFFLINE,
		
		CMD_DB_MODIFY_ROLE_HUO_BI_OFFLINE,
		
		CMD_DB_UPDATE_USR_SECOND_PASSWORD,
		
		CMD_DB_GET_USR_SECOND_PASSWORD,
		
		CMD_DB_UPDATE_MARRY_DATA,
		
		CMD_DB_GET_MARRY_DATA,
		
		CMD_DB_MARRY_PARTY_QUERY,
		
		CMD_DB_MARRY_PARTY_ADD,
		
		CMD_DB_MARRY_PARTY_REMOVE,
		
		CMD_DB_MARRY_PARTY_JOIN_INC,
		
		CMD_DB_MARRY_PARTY_JOIN_CLEAR,
		
		CMD_DB_TIANTI_ADD_ZHANBAO_LOG = 10200,
		
		CMD_DB_TIANTI_UPDATE_ROLE_DATA,
		
		CMD_DB_TIANTI_UPDATE_RONGYAO,
		
		CMD_DB_MERLIN_CREATE,
		
		CMD_DB_MERLIN_UPDATE,
		
		CMD_DB_MERLIN_QUERY,
		
		CMD_DB_UPDATE_HOLYITEM,
		
		CMD_DB_FLUORESCENT_GEM_RESET_BAG,
		
		CMD_DB_FLUORESCENT_POINT_UPDATE,
		
		CMD_DB_FLUORESCENT_EQUIP,
		
		CMD_DB_FLUORESCENT_UN_EQUIP,
		
		CMD_DB_FLUORESCENT_POINT_MODIFY,
		
		CMD_DB_QUERY_ROLEMINIINFO = 10220,
		
		CMD_DB_QUERY_USERACTIVITYINFO,
		
		CMD_DB_UPDATE_USERACTIVITYINFO,
		
		CMD_DB_ZHENGDUO_UPDATE_USEDTIME,
		
		CMD_DB_ZHENGDUO_QUERY_USEDTIME,
		
		CMD_DB_ROLECUSTOMDATA_QUERY = 10230,
		
		CMD_DB_ROLEDATA_SELECTOR_QUERY = 10232,
		
		CMD_DB_ROLECUSTOMDATA_UPDATE,
		
		CMD_DB_GET_SERVERLIST = 11000,
		
		CMD_DB_ONLINE_SERVERHEART,
		
		CMD_DB_GET_SERVERID,
		
		CMD_DB_SET_SERVER_DAY_DATA,
		
		CMD_DB_GET_SERVER_DAY_DATA,
		
		CMD_DB_GET_SERVER_PTID,
		
		CMD_NAME_REGISTERNAME = 12000,
		
		CMD_SPR_GM_SET_MAIN_TASK = 13000,
		
		CMD_DB_QUERY_USERID_VALUE,
		
		CMD_DB_SHENJI_MODIFY = 13095,
		
		CMD_DB_SHENJI_CLEAR,
		
		CMD_DB_ALCHEMY_MODIFY,
		
		CMD_DB_ALCHEMY_ROLLBACK,
		
		CMD_DB_RETURN_IS_OPEN = 13100,
		
		CMD_DB_RETURN_DATA,
		
		CMD_DB_RETURN_DATA_UPDATE,
		
		CMD_DB_RETURN_DATA_DEL,
		
		CMD_DB_RETURN_DATA_LIST,
		
		CMD_DB_RETURN_AWARD_LIST,
		
		CMD_DB_RETURN_AWARD_UPDATE,
		
		CMD_DB_RETURN_USER_CHECK,
		
		CMD_DB_TALENT_MODIFY,
		
		CMD_DB_TALENT_EFFECT_MODIFY,
		
		CMD_DB_TALENT_EFFECT_CLEAR,
		
		CMD_DB_GM_BAN_CHACK,
		
		CMD_DB_GM_BAN_LOG,
		
		CMD_DB_TEN_INIT,
		
		CMD_DB_SPREAD_AWARD_GET,
		
		CMD_DB_SPREAD_AWARD_UPDATE,
		
		CMD_DB_FUND_INFO,
		
		CMD_DB_FUND_BUY,
		
		CMD_DB_FUND_AWARD,
		
		CMD_DB_FUND_MONEY,
		
		CMD_DB_ACTIVATE_GET,
		
		CMD_DB_ACTIVATE_SET,
		
		CMD_DB_UNION_ALLY_LOG,
		
		CMD_DB_UNION_ALLY_LOG_ADD,
		
		CMD_DB_OLYMPICS_SHOP_LIST,
		
		CMD_DB_OLYMPICS_SHOP_UPDATE,
		
		CMD_DB_OLYMPICS_GUESS,
		
		CMD_DB_OLYMPICS_GUESS_LIST,
		
		CMD_DB_OLYMPICS_GUESS_UPDATE,
		
		CMD_DB_INPUTPOINTS_EXCHANGE = 13150,
		
		CMD_DB_UPDATE_INPUTPOINTS,
		
		CMD_DB_UPDATE_INPUTPOINTS_USERID,
		
		CMD_DB_UPDATE_SPECACT = 13160,
		
		CMD_DB_DELETE_SPECACT,
		
		CMD_DB_GET_SPECJIFENINFO,
		
		CMD_DB_UPDATE_SPECJIFEN,
		
		CMD_DB_GET_SPECACTINFO,
		
		CMD_DB_UPDATE_EVERYACT = 13170,
		
		CMD_DB_DELETE_EVERYACT,
		
		CMD_DB_GET_EVERYJIFENINFO,
		
		CMD_DB_UPDATE_EVERYJIFEN,
		
		CMD_DB_UPDATE_SPEC_PRIORITY_ACT = 13175,
		
		CMD_DB_DELETE_SPEC_PRIORITY_ACT,
		
		CMD_DB_QUERY_CHONGZHIMONEY_PERIOD,
		
		CMD_DB_ROLE_JIERI_GIVE_TO_OTHER = 13200,
		
		CMD_DB_SPR_GET_JIERI_GIVE_AWARD,
		
		CMD_DB_LOAD_ROLE_JIERI_GIVE_RECV_INFO,
		
		CMD_DB_LOAD_JIERI_GIVE_KING_RANK,
		
		CMD_DB_LOAD_ROLE_JIERI_GIVE_KING,
		
		CMD_DB_GET_JIERI_GIVE_KING_AWARD,
		
		CMD_DB_LOAD_JIERI_RECV_KING_RANK,
		
		CMD_DB_LOAD_ROLE_JIERI_RECV_KING,
		
		CMD_DB_GET_JIERI_RECV_KING_AWARD,
		
		CMD_DB_UPDATE_ROLE_GUARD_STATUE = 13210,
		
		CMD_DB_UPDATE_ROLE_GUARD_SOUL,
		
		CMD_DB_QUERY_JIERI_LIANXU_CHARGE = 13214,
		
		CMD_DB_UPDATE_JIERI_LIANXU_CHARGE_AWARD,
		
		CMD_DB_SPR_GET_JIERI_RECV_AWARD = 13218,
		
		CMD_DB_LOAD_ROLE_JIERI_RECV_INFO,
		
		CMD_DB_UPDATE_SEVEN_DAY_ITEM_DATA,
		
		CMD_DB_CLEAR_SEVEN_DAY_DATA,
		
		CMD_DB_GET_EACH_DAY_CHARGE,
		
		CMD_DB_UPDATE_ORNAMENT_ITEM_DATA,
		
		CMD_DB_GET_KING_ROLE_DATA = 13230,
		
		CMD_DB_PUT_KING_ROLE_DATA,
		
		CMD_DB_CLR_KING_ROLE_DATA,
		
		CMD_DB_UPDATE_BUILDING_DATA = 13300,
		
		CMD_DB_UPDATE_BUILDING_LOG,
		
		CMD_DB_CHARGEITEM_GET_DATA = 13320,
		
		CMD_DB_CHARGEITEM_DEL_DATA,
		
		CMD_DB_UPDATE_ONEPIECE_TREASURE_LOG = 13400,
		
		CMD_SPR_KF_SWITCH_SERVER = 14000,
		
		CMD_SPR_CHANGE_NAME,
		
		CMD_NTF_EACH_ROLE_ALLOW_CHANGE_NAME,
		
		CMD_NTF_CANNOT_JOIN_KUAFU_FU_BEN_END_TICKS,
		
		CMD_PLEASE_TELL_ME,
		
		CMD_DB_GET_PLAT_CHARGE_KING_LIST,
		
		CMD_SPR_CHANGE_BANGHUI_NAME,
		
		CMD_DB_LOAD_TRADE_BLACK_HOUR_ITEM,
		
		CMD_DB_SAVE_TRADE_BLACK_HOUR_ITEM,
		
		CMD_SPR_CHANGE_BANGHUI_NAME_TIMES,
		
		CMD_NTF_MAGIC_CRASH_UNITY,
		
		CMD_DB_ZHENGBA_SAVE_SUPPORT_LOG,
		
		CMD_DB_ZHENGBA_SAVE_PK_LOG,
		
		CMD_DB_ZHENGBA_LOAD_SUPPORT_LOG,
		
		CMD_DB_ZHENGBA_LOAD_PK_LOG,
		
		CMD_DB_ZHENGBA_LOAD_SUPPORT_FLAG,
		
		CMD_DB_ZHENGBA_LOAD_WAIT_AWARD_YAZHU,
		
		CMD_DB_ZHENGBA_SET_YAZHU_AWARD_FLAG,
		
		CMD_DB_BHMATCH_LOAD_SUPPORT_FLAG = 14020,
		
		CMD_DB_BHMATCH_UPDATE_SUPPORT_FLAG,
		
		CMD_DB_UPDATA_FUMOMONEY_ACCEPTNUM = 14101,
		
		CMD_DB_INSERT_FUMOMAIL,
		
		CMD_DB_GET_FUMOMAIL_NUM_INDEX,
		
		CMD_DB_INSERT_FUMOMAIL_TEMP,
		
		CMD_DB_GET_FUMOMAIL_MAP_ACCEPT,
		
		CMD_DB_GET_FUMOMONEY_MAIL_LIST,
		
		CMD_DB_GET_FUMOMAIL_MAP_LIST,
		
		CMD_DB_UPDATE_FUMOMAIL_MAP,
		
		CMD_DB_DELETE_FUMOMAIL,
		
		CMD_DB_DELETE_FUMOMAIL_LIST,
		
		CMD_DB_UPDATE_FUMOMAIL_STATE_READ,
		
		CMD_DB_INSERT_REBORNYINJI = 14115,
		
		CMD_DB_UPDATESTAMP_REBORNYINJI,
		
		CMD_DB_GETINFO_REBORNYINJI,
		
		CMD_DB_REBORN_BAGNUM,
		
		CMD_DB_REBORN_STORENUM,
		
		CMD_DB_REBORN_SHOWEQUIP,
		
		CMD_DB_REBORN_SHOWMODEL = 14122,
		
		CMD_DB_REBORN_INSERT_HOLEINFO,
		
		CMD_DB_REBORN_UPDATE_HOLEINFO,
		
		CMD_DB_MAZINGER_INSERTINFO,
		
		CMD_DB_MAZINGER_UPDATEINFO,
		
		CMD_DB_REGRESSACTIVE_GETREGTIME = 14130,
		
		CMD_DB_REGRESSACTIVE_INSERTSING,
		
		CMD_DB_REGRESSACTIVE_GETSIGNINFO,
		
		CMD_DB_REGRESSACTIVE_GETSTOREINFO,
		
		CMD_DB_REGRESSACTIVE_GETSTOREGOODINFO,
		
		CMD_DB_REGRESSACTIVE_INSERTSTORE,
		
		CMD_DB_REGRESSACTIVE_GETINPUTINFO,
		
		CMD_DB_REGRESSACTIVE_GETDAYSIGNINFO,
		
		CMD_DB_REGRESSACTIVE_UPDATESING,
		
		CMD_LOGDB_ADD_ITEM_LOG = 20000,
		
		CMD_LOGDB_ADD_TRADEMONEY_FREQ_LOG,
		
		CMD_LOGDB_ADD_TRADEMONEY_NUM_LOG,
		
		CMD_LOGDB_UPDATE_ROLE_KUAFU_DAY_LOG,
		
		CMD_DB_FACEBOOK_INIT = 21000,
		
		CMD_DB_UPDATA_TAROT = 20100,
		
		CMD_DB_AOYUN_DATI_GET_ROLELIST = 20300,
		
		CMD_DB_AOYUN_DATI_GET_LASTRANK,
		
		CMD_DB_AOYUN_DATI_SET_LASTRANK,
		
		CMD_DB_AOYUN_DATI_POINT_CLEAN,
		
		CMD_DB_GETROLEPARAM,
		
		CMD_DB_WEBOLDPLAYER_UPDATE,
		
		CMD_DB_GET_YAOSAIBOSS_DATA,
		
		CMD_DB_SET_YAOSAIBOSS_DATA,
		
		CMD_DB_GET_BOSSFIGHT_LOG,
		
		CMD_DB_SET_BOSSFIGHT_LOG,
		
		CMD_DB_CLEAN_BOSSDATA,
		
		CMD_DB_GET_YAOSAIMISSION_DATA,
		
		CMD_DB_SET_YAOSAIMISSION_DATA,
		
		CMD_DB_DEL_YAOSAIMISSION_DATA,
		
		CMD_DB_GETGOODSLISTBYSITE_RANGE,
		
		CMD_DB_ADD_FUWENTABDATA,
		
		CMD_DB_UPDATE_FUWENTABDATA,
		
		CMD_DB_GETJUEXING_DATA,
		
		CMD_DB_UPDATEJUEXING_DATA,
		
		CMD_DB_GETMOUNT_DATA,
		
		CMD_DB_SETMOUNT_DATA,
		
		CMD_DB_MOUNT_CHECK,
		
		CMD_DB_GM_SUBROLEHUOBI = 20398,
		
		CMD_LINYL_ZHANYONG,
		
		CMD_SPR_TASKLIST_DATA = 29900,
		
		CMD_SPR_TASKLIST_KEY = 30000,
		
		CMD_SPR_TASKLIST_NOTIFY,
		
		CMD_DB_GET_ZONEID_UID_BY_RID = 30010,
		
		CMD_DB_ERR_RETURN = 30767
	}
}
