using System;

namespace GameServer
{
	
	public enum LangTexts
	{
		
		TEXT_DUNHAO = 1,
		
		TEXT_WU,
		
		TEXT_MONSTER_NAME,
		
		TEXT_DATATODATA,
		
		TEXT_MONDAY,
		
		TEXT_TUESDAY,
		
		TEXT_WEDNESSDAY,
		
		TEXT_THURSDAY,
		
		TEXT_FRIDAY,
		
		TEXT_SATURDAY,
		
		TEXT_SUNDAY,
		
		TEXT_GUARD_NAME,
		
		TEXT_ATTACK,
		
		TEXT_DEFENSE,
		
		TEXT_LIFE,
		
		TEXT_KF5V5_ZIYOU_JIANG_SUJECT = 1421,
		
		TEXT_KF5V5_ZIYOU_JIANG_WIN_CONTENT,
		
		TEXT_KF5V5_ZIYOU_JIANG_LOSE_CONTENT,
		
		TEXT_KF5V5_YUEDU_AWARD_SUBJECT,
		
		TEXT_KF5V5_YUEDU_KILL_AWARD_CONTENT,
		
		TEXT_KF5V5_YUEDU_WIN_AWARD_CONTENT,
		
		TEXT_KF5V5_YUEDU_RANK_AWARD_CONTENT,
		
		TEXT_KF5V5_64QIANG_EMPTYROUND_SUBJECT,
		
		TEXT_KF5V5_64QIANG_EMPTYROUND_CONTENT,
		
		TEXT_KF5V5_64QIANG_BATTLE_SUBJECT,
		
		TEXT_KF5V5_64QIANG_BATTLE_CONTENT,
		
		TEXT_KF5V5_64QIANG_TODAY,
		
		TEXT_KF5V5_64QIANG_TOMMORROW,
		
		TEXT_KF5V5_64QIANG_ROUND1,
		
		TEXT_KF5V5_64QIANG_ROUND2,
		
		TEXT_KF5V5_64QIANG_ROUND3,
		
		TEXT_KF5V5_64QIANG_ROUND4,
		
		TEXT_KF5V5_64QIANG_ROUND5,
		
		TEXT_KF5V5_64QIANG_ROUND6,
		
		TEXT_KF5V5_64QIANG_WINNER_SUBJECT,
		
		TEXT_KF5V5_64QIANG_WINNER_CONTENT,
		
		TEXT_KF5V5_64QIANG_WINNER_AWARD_SUBJECT,
		
		TEXT_KF5V5_64QIANG_WINNER_AWARD_CONTENT,
		
		TEXT_KF5V5_64QIANG_AWARD_SUBJECT,
		
		TEXT_KF5V5_64QIANG_AWARD_CONTENT,
		
		TEXT_KF5V5_64QIANG_YAZHU_SUCCESS_SUBJECT,
		
		TEXT_KF5V5_64QIANG_YAZHU_SUCCESS_CONTENT,
		
		TEXT_KF5V5_64QIANG_YAZHU_FAILED_SUBJECT,
		
		TEXT_KF5V5_64QIANG_YAZHU_FAILED_CONTENT
	}
}
