using System;

namespace LogDBServer.Server
{
	
	internal enum TCPGameServerCmds
	{
		
		CMD_LOGIN_ON1 = 1,
		
		CMD_LOGIN_ON2 = 20,
		
		CMD_LOG_OUT = 22,
		
		CMD_LOGIN_ON = 100,
		
		CMD_ROLE_LIST,
		
		CMD_CREATE_ROLE,
		
		CMD_REMOVE_ROLE,
		
		CMD_INIT_GAME,
		
		CMD_SYNC_TIME,
		
		CMD_PLAY_GAME,
		
		CMD_SPR_MOVE,
		
		CMD_SPR_MOVEEND,
		
		CMD_SPR_MOVE2,
		
		CMD_OTHER_ROLE,
		
		CMD_OTHER_ROLE_DATA,
		
		CMD_SPR_POSITION,
		
		CMD_SPR_PETPOS,
		
		CMD_SPR_ACTTION,
		
		CMD_SPR_ACTTION2,
		
		CMD_SPR_MAGICCODE,
		
		CMD_SPR_ATTACK,
		
		CMD_SPR_INJURE,
		
		CMD_SPR_REALIVE,
		
		CMD_SPR_RELIFE,
		
		CMD_SPR_CLICKON,
		
		CMD_SYSTEM_MONSTER,
		
		CMD_SPR_MAPCHANGE,
		
		CMD_LOG_OUT_Unused_Dont_Del,
		
		CMD_SPR_NEWTASK,
		
		CMD_SPR_GETATTRIB2,
		
		CMD_SPR_LEAVE,
		
		CMD_SPR_NPC_BUY,
		
		CMD_SPR_NPC_SALEOUT,
		
		CMD_SPR_ADD_GOODS,
		
		CMD_SPR_MOD_GOODS,
		
		CMD_SPR_MERGE_GOODS,
		
		CMD_SPR_SPLIT_GOODS,
		
		CMD_SPR_GET_MERGETYPES,
		
		CMD_SPR_GET_MERGEITEMS,
		
		CMD_SPR_GET_MERGENEWGOODS,
		
		CMD_SPR_CHGCODE,
		
		CMD_SPR_MONEYCHANGE,
		
		CMD_SPR_MODTASK,
		
		CMD_SPR_COMPTASK,
		
		CMD_SPR_EXPCHANGE,
		
		CMD_SPR_GETFRIENDS,
		
		CMD_SPR_ADDFRIEND,
		
		CMD_SPR_REMOVEFRIEND,
		
		CMD_SPR_NEWGOODSPACK,
		
		CMD_SPR_DELGOODSPACK,
		
		CMD_SPR_CLICKONGOODSPACK,
		
		CMD_SPR_GETTHING,
		
		CMD_SPR_CHGPKMODE,
		
		CMD_SPR_CHGPKVAL,
		
		CMD_SPR_UPDATENPCSTATE,
		
		CMD_SPR_NPCSTATELIST,
		
		CMD_SPR_GETNEWTASKDATA,
		
		CMD_SPR_ABANDONTASK,
		
		CMD_SPR_HITED,
		
		CMD_SPR_MODKEYS,
		
		CMD_SPR_CHAT,
		
		CMD_SPR_USEGOODS,
		
		CMD_SPR_CHANGEPOS,
		
		CMD_SPR_NOTIFYCHGMAP,
		
		CMD_SPR_FORGE,
		
		CMD_SPR_ENCHANCE,
		
		CMD_SPR_GETOTHERATTRIB,
		
		CMD_SPR_UPDATE_ROLEDATA,
		
		CMD_SPR_REMOVE_COOLDOWN,
		
		CMD_SPR_MALL_BUY,
		
		CMD_SPR_YINLIANG_BUY,
		
		CMD_SPR_USERMONEYCHANGE,
		
		CMD_SPR_USERYINLIANGCHANGE,
		
		CMD_SPR_GOODSEXCHANGE,
		
		CMD_SPR_EXCHANGEDATA,
		
		CMD_SPR_MOVEGOODSDATA,
		
		CMD_SPR_GOODSSTALL,
		
		CMD_SPR_STALLDATA,
		
		CMD_SPR_STALLNAME,
		
		CMD_SPR_TEAM,
		
		CMD_SPR_TEAMDATA,
		
		CMD_SPR_TEAMID,
		
		CMD_SPR_BATTLE,
		
		CMD_SPR_NPCSCRIPT,
		
		CMD_SPR_DEAD,
		
		CMD_SPR_AUTOFIGHT,
		
		CMD_SPR_HORSE,
		
		CMD_SPR_PET,
		
		CMD_SPR_DIANJIANGLIST,
		
		CMD_SPR_DIANJIANGDATA,
		
		CMD_SPR_DJROOMROLESDATA,
		
		CMD_SPR_DIANJIANG,
		
		CMD_SPR_DIANJIANGFIGHT,
		
		CMD_SPR_DIANJIANGPOINT,
		
		CMD_SPR_GETDJPOINTS,
		
		CMD_SPR_UPDATEINTERPOWER,
		
		CMD_SPR_GOTOMAP,
		
		CMD_SPR_NOTIFYMSG,
		
		CMD_SPR_QUERYIDBYNAME,
		
		CMD_ADDHORSE,
		
		CMD_ADDPET,
		
		CMD_GETHORSELIST,
		
		CMD_GETOTHERHORSELIST,
		
		CMD_GETPETLIST,
		
		CMD_MODHORSE,
		
		CMD_MODPET,
		
		CMD_SELECTHORSE,
		
		CMD_GETGOODSLISTBYSITE,
		
		CMD_GETLINEINFO,
		
		CMD_GETJINGMAILIST,
		
		CMD_UP_JINGMAI_LEVEL,
		
		CMD_GETOTHERJINGMAILIST,
		
		CMD_SPR_LOADALREADY,
		
		CMD_SPR_BULLETINMSG,
		
		CMD_SPR_GMAUTH,
		
		CMD_SPR_EQUIPUPGRADE,
		
		CMD_SPR_ENCHASEJEWEL,
		
		CMD_SPR_SHOWBIGUAN,
		
		CMD_SPR_GETBIGUAN,
		
		CMD_SPR_UPSKILLLEVEL,
		
		CMD_SPR_ADD_SKILL,
		
		CMD_SPR_JINGMAI_INFO,
		
		CMD_SPR_HORSEENCHANCE,
		
		CMD_SPR_HORSEUPGRADE,
		
		CMD_SPR_SALEGOODS,
		
		CMD_SPR_SELFSALEGOODSLIST,
		
		CMD_SPR_OTHERSALEGOODSLIST,
		
		CMD_SPR_MARKETROLELIST,
		
		CMD_SPR_MARKETGOODSLIST,
		
		CMD_SPR_MARKETBUYGOODS,
		
		CMD_SPR_MODDEFSKILLID,
		
		CMD_SPR_MODAUTODRINK,
		
		CMD_SPR_PLAYDECO,
		
		CMD_SPR_BUFFERDATA,
		
		CMD_SPR_RUNTOMAP,
		
		CMD_SPR_SEARCHROLES,
		
		CMD_SPR_LISTROLES,
		
		CMD_SPR_LISTTEAMS,
		
		CMD_SPR_RESETBAG,
		
		CMD_SPR_DAILYTASKDATA,
		
		CMD_SPR_DAILYJINGMAIDATA,
		
		CMD_SPR_CHGNUMSKILLID,
		
		CMD_SPR_GETSKILLUSEDNUM,
		
		CMD_SPR_CHGHORSEBODY,
		
		CMD_SPR_PORTABLEBAGDATA,
		
		CMD_SPR_RESETPORTABLEBAG,
		
		CMD_SPR_EXECWABAO,
		
		CMD_SPR_GETWABAODATA,
		
		CMD_SPR_GETHUODONGDATA,
		
		CMD_SPR_GETWLOGINGIFT,
		
		CMD_SPR_GETNEWSTEPGIFT,
		
		CMD_SPR_GETMTIMEGIFT,
		
		CMD_SPR_GETBIGGIFT,
		
		CMD_SPR_GETSONGLIGIFT,
		
		CMD_SPR_CHGHUODONGID,
		
		CMD_SPR_FUBENDATA,
		
		CMD_SPR_ENTERFUBEN,
		
		CMD_SPR_NOTIFYENTERFUBEN,
		
		CMD_SPR_CLIENTHEART,
		
		CMD_SPR_OHTERJINGMAIEXP,
		
		CMD_GETRANDOMNAME,
		
		CMD_SKILLUSEDNUMFULL,
		
		CMD_SPR_GETFUBENHISTDATA,
		
		CMD_SPR_GETFUBENBEGININFO,
		
		CMD_SPR_COPYMAPMONSTERSNUM,
		
		CMD_SPR_FINDMONSTER,
		
		CMD_SPR_BATCHYINPIAO,
		
		CMD_SPR_FORCETOLAOFANG,
		
		CMD_SPR_CHGPURPLENAME,
		
		CMD_SPR_CHGLIANZHAN,
		
		CMD_SPR_GETROLEDAILYDATA,
		
		CMD_SPR_GETBOSSINFODICT,
		
		CMD_SPR_GETPAIHANGLIST,
		
		CMD_SPR_YABIAODATA,
		
		CMD_SPR_STARTYABIAO,
		
		CMD_SPR_ENDYABIAO,
		
		CMD_SPR_YABIAOTAKEGOODS,
		
		CMD_SPR_TOUBAO,
		
		CMD_SPR_GETOTHERATTRIB2,
		
		CMD_SPR_NEWBIAOCHE,
		
		CMD_SPR_DELBIAOCHE,
		
		CMD_SPR_FINDBIAOCHE,
		
		CMD_SPR_CHGBIAOCHELIFEV,
		
		CMD_SPR_NOTIFYENDCHONGXUE,
		
		CMD_SPR_ADDHORSELUCKY,
		
		CMD_SPR_BATTLEKILLEDNUM,
		
		CMD_SPR_CHGBATTLENAMEINFO,
		
		CMD_SPR_NOFITYPOPUPWIN,
		
		CMD_SPR_NOTIFYBATTLEROLEINFO,
		
		CMD_SPR_NOTIFYBATTLEENDINFO,
		
		CMD_SPR_GETCHONGZHIJIFEN,
		
		CMD_SPR_NOTIFYTEAMCHGLEVEL,
		
		CMD_SPR_GETFUBENHISTLISTDATA,
		
		CMD_SPR_CHGHEROINDEX,
		
		CMD_GETOTHERHORSEDATA,
		
		CMD_UPDATEALLTHINGINDEXS,
		
		CMD_SPR_CHGHALFYINLIANGPERIOD,
		
		CMD_SPR_GETBANGHUILIST,
		
		CMD_SPR_CREATEBANGHUI,
		
		CMD_SPR_CHGBANGHUIINFO,
		
		CMD_SPR_QUERYBANGHUIDETAIL,
		
		CMD_SPR_UPDATEBANGHUIBULLETIN,
		
		CMD_SPR_GETBHMEMBERDATALIST,
		
		CMD_SPR_UPDATEBHVERIFY,
		
		CMD_SPR_APPLYTOBHMEMBER,
		
		CMD_SPR_ADDBHMEMBER,
		
		CMD_SPR_REMOVEBHMEMBER,
		
		CMD_SPR_QUITFROMBANGHUI,
		
		CMD_SPR_DESTROYBANGHUI,
		
		CMD_SPR_BANGHUIVERIFY,
		
		CMD_SPR_INVITETOBANGHUI,
		
		CMD_SPR_CHGBHMEMBERZHIWU,
		
		CMD_SPR_CHGBHMEMBERCHENGHAO,
		
		CMD_SPR_SEARCHROLESFROMDB,
		
		CMD_SPR_AGREETOTOBANGHUI,
		
		CMD_SPR_REFUSEAPPLYTOBH,
		
		CMD_SPR_GETBANGGONGHIST,
		
		CMD_SPR_DONATEBGMONEY,
		
		CMD_SPR_DONATEBGGOODS,
		
		CMD_SPR_BANGGONGCHANGE,
		
		CMD_SPR_GETBANGQIINFO,
		
		CMD_SPR_RENAMEBANGQI,
		
		CMD_SPR_UPLEVELBANGQI,
		
		CMD_SPR_CHGJUNQILIFEV,
		
		CMD_SPR_NEWJUNQI,
		
		CMD_SPR_DELJUNQI,
		
		CMD_SPR_LINGDIFORBH,
		
		CMD_SPR_CHGHUANGDIROLEID,
		
		CMD_SPR_GETBHLINGDIINFODICTBYBHID,
		
		CMD_SPR_SETLINGDITAX,
		
		CMD_SPR_TAKELINGDITAXMONEY,
		
		CMD_SPR_GETHUANGDIBHINFO,
		
		CMD_SPR_NOTIFYBHZHIWU,
		
		CMD_SPR_OPENYANGGONGBK,
		
		CMD_SPR_REFRESHYANGGONGBK,
		
		CMD_SPR_CLICKYANGGONGBK,
		
		CMD_SPR_REFRESHQIZHENGE,
		
		CMD_SPR_QIZHEGEBUY,
		
		CMD_SPR_QUERYQIZHEGEBUYHIST,
		
		CMD_SPR_QUICKJINGMAI,
		
		CMD_SPR_QUICKHORSEENCHANCE,
		
		CMD_SPR_QUICKEQUIPENHANCE,
		
		CMD_SPR_QUICKEQUIPFORGE,
		
		CMD_SPR_GETHUANGDIROLEDATA,
		
		CMD_SPR_ADDHUANGFEI,
		
		CMD_SPR_REMOVEHUANGFEI,
		
		CMD_SPR_GETHUANGFEIDATA,
		
		CMD_SPR_SENDTOLAOFANG,
		
		CMD_SPR_TAKEOUTLAOFANG,
		
		CMD_SPR_BANCHAT,
		
		CMD_SPR_CHGHUANGHOU,
		
		CMD_SPR_GETLINGDIMAPINFO,
		
		CMD_SPR_GETHUANGCHENGMAPINFO,
		
		CMD_SPR_ADDLINGDITAXMONEY,
		
		CMD_SPR_INVITEADDHUANGFEI,
		
		CMD_SPR_AGREEADDHUANGFEI,
		
		CMD_SPR_TASKTRANSPORT,
		
		CMD_SPT_LINGLIGUANZHU,
		
		CMD_SPR_GETGOODSBYDBID,
		
		CMD_SPR_QUICKCOMPLETETASK,
		
		CMD_SPR_QUERYCHONGZHIMONEY,
		
		CMD_SPR_GETFIRSTCHONGZHIDALI,
		
		CMD_SPR_NOTIFYBATTLESIDE,
		
		CMD_SPR_NOTIFYBATTLEAWARD,
		
		CMD_SPR_EXECWABAOBYYAOSHI,
		
		CMD_SPR_SUBFORGE,
		
		CMD_SPR_GETUSERMAILLIST,
		
		CMD_SPR_GETUSERMAILDATA,
		
		CMD_SPR_FETCHMAILGOODS,
		
		CMD_SPR_DELETEUSERMAIL,
		
		CMD_SPR_GETMAILSENDCODE,
		
		CMD_SPR_SENDUSERMAIL,
		
		CMD_SPR_RECEIVELASTMAIL,
		
		CMD_SPR_EQUIPBORNINDEXUPDATE,
		
		CMD_SPR_EQUIPINHERIT,
		
		CMD_SPR_QUERYINPUTFANLI,
		
		CMD_SPR_QUERYINPUTJIASONG,
		
		CMD_SPR_QUERYINPUTKING,
		
		CMD_SPR_QUERYLEVELKING,
		
		CMD_SPR_QUERYEQUIPKING,
		
		CMD_SPR_QUERYHORSEKING,
		
		CMD_SPR_QUERYJINGMAIKING,
		
		CMD_SPR_QUERYAWARDHIST,
		
		CMD_SPR_EXECUTEINPUTFANLI,
		
		CMD_SPR_EXECUTEINPUTJIASONG,
		
		CMD_SPR_EXECUTEINPUTKING,
		
		CMD_SPR_EXECUTELEVELKING,
		
		CMD_SPR_EXECUTEEQUIPKING,
		
		CMD_SPR_EXECUTEHORSEKING,
		
		CMD_SPR_EXECUTEJINGMAIKING,
		
		CMD_SPR_MALLZHENQIBUY,
		
		CMD_SPR_FETCHACTIVITYAWARD,
		
		CMD_SPR_VIPDAILYDATA,
		
		CMD_SPR_USEVIPDAILYPRIORITY,
		
		CMD_SPR_ACTIVITYTRANSPORT,
		
		CMD_SPR_YANGGONGBKDAILYDATA,
		
		CMD_SPR_FETCHYANGGONGBKJIFENAWARD,
		
		CMD_SPR_QUERYSHILIANTAAWARDINFO,
		
		CMD_SPR_FETCHSHILIANTAAWARD,
		
		CMD_SPR_COMPLETETINYCLIENT,
		
		CMD_SPR_USERGOLDCHANGE,
		
		CMD_SPR_NOTIFYSHENGXIAOGUESSSTAT,
		
		CMD_SPR_NOTIFYSHENGXIAOGUESSRESULT,
		
		CMD_SPR_ADDSHENGXIAOMORTGAGE,
		
		CMD_SPR_QUERYROLESHENGXIAOGUESSLIST,
		
		CMD_SPR_QUERYSHENGXIAOGUESSHISTORY,
		
		CMD_SPR_QUERYSHENGXIAORECENTRESULTLIST,
		
		CMD_SPR_QUERYSHENGXIAOGUESSSELFHISTORY,
		
		CMD_SPR_UPDATETENGXUNFCMRATE,
		
		CMD_SPR_NEWNPC,
		
		CMD_SPR_DELNPC,
		
		CMD_SPR_EXTGRIDBYYUANBAO,
		
		CMD_SPR_SUBMONEY,
		
		CMD_SPR_EXTBAGNUMBYYUANBAO,
		
		CMD_SPR_STOPMOVE,
		
		CMD_SPR_NOTIFYEQUIPSTRONG,
		
		CMD_SPR_EXCUTENPCLUATALK,
		
		CMD_SPR_EXCUTENPCLUAFUNCTION,
		
		CMD_SPR_ARENABATTLE,
		
		CMD_SPR_ARENABATTLEKILLEDNUM,
		
		CMD_SPR_CITYWARREQUEST,
		
		CMD_SPR_TAKELINGDIDAILYAWARD,
		
		CMD_SPR_NOTIFYOPENWINDOW,
		
		CMD_SPR_CHENGJIUDATA,
		
		CMD_SPR_FETCHCHENGJIUAWARD,
		
		CMD_SPR_DSHIDECMD,
		
		CMD_SPR_NEWDECO,
		
		CMD_SPR_DELDECO,
		
		CMD_SPR_MENDEQUIPMENT,
		
		CMD_SPR_NOTIFYGOODSINFO,
		
		CMD_SPR_ROLEPARAMSCHANGE,
		
		CMD_SPR_EQUIPFENJIE,
		
		CMD_SPR_JINGYUANEXCHANGE,
		
		CMD_SPR_HUIZHANGEXCHANGE,
		
		CMD_SPR_ACTIVATNEXTLEVELJINGMAI,
		
		CMD_SPR_FETCHVIPONCEAWARD,
		
		CMD_SPR_TASKTRANSPORT2,
		
		CMD_SPR_ACTIVATNEXTLEVELWUXUE,
		
		CMD_SPR_CAIJI,
		
		CMD_SPR_RUNTASKPLOTLUA,
		
		CMD_SPR_PLAYGAMEEFFECT,
		
		CMD_SPR_TRANSFERSOMETHING,
		
		CMD_SPR_CHANGEPETAITYPE,
		
		CMD_SPR_FETCHMALLDATA,
		
		CMD_SPR_MALLQIANGGOUBUYGOODS,
		
		CMD_SPR_FETCHZUANHUANGAWARD,
		
		CMD_SPR_SETSYSTEMOPENPARAMS,
		
		CMD_SPR_ENTERTASKFUBEN,
		
		CMD_SPR_GETUPLEVELGIFTOK,
		
		CMD_SPR_UPDATEWEIGHTS,
		
		CMD_SPR_GETTASKAWARDS,
		
		CMD_SPR_NOTIFYGETGOODSPACK,
		
		CMD_SPR_RESETJINDANBAG,
		
		CMD_SPR_GETJINDANGOODSLIST,
		
		CMD_SPR_ZAJINDAN,
		
		CMD_SPR_QUERYZAJINDANHISTORY,
		
		CMD_SPR_QUERYSELFZAJINDANHISTORY,
		
		CMD_SPR_GETWANGCHENGMAPINFO,
		
		CMD_SPR_GETLIMITTIMELOGINGIFT,
		
		CMD_SPR_ROLESTATUSCMD,
		
		CMD_SPR_GETTO60AWARD,
		
		CMD_SPR_GETKAIFUONLINEINFO,
		
		CMD_SPR_GETDAYCHONGZHIDALI,
		
		CMD_SPR_GETJIERIXMLDATA,
		
		CMD_SPR_QUERYJIERIDALIBAO,
		
		CMD_SPR_QUERYJIERIDENGLU,
		
		CMD_SPR_QUERYJIERIVIP,
		
		CMD_SPR_QUERYJIERICZSONG,
		
		CMD_SPR_QUERYJIERICZLEIJI,
		
		CMD_SPR_QUERYJIERIZIKA,
		
		CMD_SPR_QUERYJIERIXIAOFEIKING,
		
		CMD_SPR_QUERYJIERICZKING,
		
		CMD_SPR_EXECUTEJIERIDALIBAO,
		
		CMD_SPR_EXECUTEJIERIDENGLU,
		
		CMD_SPR_EXECUTEJIERIVIP,
		
		CMD_SPR_EXECUTEJIERICZSONG,
		
		CMD_SPR_EXECUTEJIERICZLEIJI,
		
		CMD_SPR_EXECUTEJIERIZIKA,
		
		CMD_SPR_EXECUTEJIERIXIAOFEIKING,
		
		CMD_SPR_EXECUTEJIERICZKING,
		
		CMD_SPR_CHGJIERICHENGHAO,
		
		CMD_SPR_FACTIVITIESDATA,
		
		CMD_SPR_YUANBAOCOMPLETETASK,
		
		CMD_SPR_QUERYHEFUDALIBAO,
		
		CMD_SPR_QUERYHEFUVIP,
		
		CMD_SPR_QUERYHEFUCZSONG,
		
		CMD_SPR_QUERYHEFUFANLI,
		
		CMD_SPR_QUERYHEFUPKKING,
		
		CMD_SPR_QUERYHEFUWCKING,
		
		CMD_SPR_QUERYXINFANLI,
		
		CMD_SPR_EXECUHEFUDALIBAO,
		
		CMD_SPR_EXECUHEFUVIP,
		
		CMD_SPR_EXECUHEFUCZSONG,
		
		CMD_SPR_EXECUHEFUFANLI,
		
		CMD_SPR_EXECUHEFUPKKING,
		
		CMD_SPR_EXECUHEFUWCKING,
		
		CMD_SPR_EXECUXINFANLI,
		
		CMD_SPR_ONEKEYQUICKSALEOUT,
		
		CMD_SPR_ACTIVATNEXTLEVELZHANHUN,
		
		CMD_SPR_ACTIVATNEXTLEVELRONGYU,
		
		CMD_SPR_ACTIVATRONGYUBUFFER,
		
		CMD_SPR_LIANLUJINGLIAN,
		
		CMD_SPR_ZJDJIFEN,
		
		CMD_SPR_FETCHZJDJIFENAWARD,
		
		CMD_SPR_QUERYACTIVITYINFO,
		
		CMD_SPR_XINGYUNCHOUJIANG,
		
		CMD_SPR_QUERYYUEDUCHOUJIANGHISTORY,
		
		CMD_SPR_QUERYSELFQUERYYUEDUCHOUJIANGHISTORY,
		
		CMD_SPR_EXECUTEYUEDUCHOUJIANG,
		
		CMD_SPR_QUERYYUEDUCHOUJIANGINFO,
		
		CMD_SPR_EXECUTEHUNQIEXCHANGE,
		
		CMD_SPR_EXECUTECHANGEOCCUPATION,
		
		CMD_SPR_EXECUTECHANGELIFE,
		
		CMD_SPR_BEGINBLINK,
		
		CMD_SPR_ENDBLINK,
		
		CMD_SPR_GETROLEUSINGGOODSDATALIST,
		
		CMD_SPR_EXECUTEPROPADDPOINT,
		
		CMD_SPR_EXECUTERECOMMENDPROPADDPOINT,
		
		CMD_SPR_EXECUTERECLEANPROPADDPOINT,
		
		CMD_SPR_QUERYCLEANPROPADDPOINT,
		
		CMD_SPR_BLOODCASTLEBEGINFIGHT,
		
		CMD_SPR_BLOODCASTLEKILLMONSTERAHASDONE,
		
		CMD_SPR_BLOODCASTLEENDFIGHT,
		
		CMD_SPR_FUBENCLEANOUT,
		
		CMD_SPR_FUBENPASSNOTIFY,
		
		CMD_SPR_QUERYFUBENINFO,
		
		CMD_SPR_ATTACK2,
		
		CMD_SPR_COMPLETEFLASHSCENE,
		
		CMD_SPR_FRESHPLAYERSCENEKILLMONSTERAHASDONE,
		
		CMD_SPR_REFURBISHTASKSTARLEVEL,
		
		CMD_SPR_COMPLETEDAILYCIRCLETASKFORONCECLICK,
		
		CMD_SPR_ADMIREDPLAYER,
		
		CMD_SPR_QUERYBLOODCASTLEINFO,
		
		CMD_SPR_EQUIPAPPENDPROP,
		
		CMD_SPR_BLOODCASTLEPREPAREFIGHT,
		
		CMD_SPR_BLOODCASTLECOMBATPOINT,
		
		CMD_SPR_BLOODCASTLEKILLMONSTERSTATUS,
		
		CMD_SPR_QUERYCAMPBATTLEINFO,
		
		CMD_SPR_QUERYDAIMONSQUAREINFO,
		
		CMD_SPR_QUERYDAIMONSQUARETIMERINFO,
		
		CMD_SPR_QUERYDAIMONSQUAREMONSTERWAVEANDPOINTRINFO,
		
		CMD_SPR_DAIMONSQUAREENDFIGHT,
		
		CMD_SPR_UPDATEEVERYDAYONLINEAWARDGIFTINFO,
		
		CMD_SPR_GETEVERYDAYONLINEAWARDGIFT,
		
		CMD_SPR_UPDATEEVERYDAYSERIESLOGININFO,
		
		CMD_SPR_GETEVERYDAYSERIESLOGINAWARDGIFT,
		
		CMD_SPR_FRESHPLAYERSCENEOVERTIME,
		
		CMD_SPR_UPDATEGETTHINGSFLAG,
		
		CMD_SPR_BLOODCASTLEPLAYERNUMNOTIFY,
		
		CMD_SPR_DAIMONSQUAREPLAYERNUMNOTIFY,
		
		CMD_SPR_BATTLEPLAYERNUMNOTIFY,
		
		CMD_SPR_EXCHANGEMOJINGANDQIFU,
		
		CMD_SPR_GETMEDITATEEXP,
		
		CMD_SPR_GETMEDITATETIMEINFO,
		
		CMD_SPR_QUERYTOTALLOGININFO,
		
		CMD_SPR_GETTOTALLOGINAWARD,
		
		CMD_SPR_CHANGELIFEFOREQUIP,
		
		CMD_SPR_FLAKEOFFCHANGELIFEFOREQUIP,
		
		CMD_SPR_ONEKEYFINDFRIEND,
		
		CMD_SPR_ONEKEYADDFRIEND,
		
		CMD_SPR_GETVIPAWARD,
		
		CMD_SPR_DAILYACTIVEDATA,
		
		CMD_SPR_GETDAILYACTIVEAWARD,
		
		CMD_SPR_SETAUTOASSIGNPROPERTYPOINT,
		
		CMD_SPR_GETBLOODCASTLEAWARD,
		
		CMD_SPR_GETDAIMONSQUAREAWARD,
		
		CMD_SPR_GETCOPYMAPAWARD,
		
		CMD_SPR_GETSKILLINFO,
		
		CMD_SPR_EXPERIENCECOPYMAPINFO,
		
		CMD_SPR_ZHANMENGSHIJIAN_DETAIL,
		
		CMD_SPR_KAIFUACTIVITYINFO,
		
		CMD_SPR_GETTHEKINGOFPKINFO,
		
		CMD_SPR_NOTIFYTHEKINGOFPKAWARDINFO,
		
		CMD_SPR_ANGELTEMPLETIMERINFO,
		
		CMD_SPR_ANGELTEMPLEFIGHTEND,
		
		CMD_SPR_ANGELTEMPLEFIGHTINFOALL,
		
		CMD_SPR_ANGELTEMPLEFIGHTINFOSINGLE,
		
		CMD_SPR_ANGELTEMPLESPARK,
		
		CMD_SPR_GETANGELTEMPLEBASEINFO,
		
		CMD_SPR_QUERYADRATIONPKKINGINFO,
		
		CMD_SPR_ADRATIONPKKING,
		
		CMD_SPR_JINGJI_DETAIL,
		
		CMD_SPR_JINGJI_REQUEST_CHALLENGE,
		
		CMD_SPR_JINGJI_CHALLENGE_END,
		
		CMD_SPR_JINGJI_NOTIFY_START,
		
		CMD_SPR_JINGJI_CHALLENGEINFO,
		
		CMD_SPR_JINGJI_RANKING_REWARD,
		
		CMD_SPR_JINGJICHANG_REMOVE_CD,
		
		CMD_SPR_JINGJICHANG_GET_BUFF,
		
		CMD_SPR_JINGJICHANG_JUNXIAN_LEVELUP,
		
		CMD_SPR_JINGJICHANG_LEAVE,
		
		CMD_SPR_CHGFAKEROLELIFEV,
		
		CMD_SPR_NEWFAKEROLE,
		
		CMD_SPR_DELFAKEROLE,
		
		CMD_SPR_OPENMARKET,
		
		CMD_SPR_MARKETSALEMONEY,
		
		CMD_SPR_GETVIPINFO,
		
		CMD_SPR_GETVIPLEVELAWARD,
		
		CMD_SPR_VIPLEVELUP,
		
		CMD_SPR_GETLIXIANBAITANTICKS,
		
		CMD_SPR_UPDATELIXIANBAITANTICKS,
		
		CMD_SPR_QUERYOPENGRIDTICK,
		
		CMD_SPR_QUERYOPENPORTABLEGRIDTICK,
		
		CMD_SPR_STARTMEDITATE,
		
		CMD_SPR_ZHANMENGBUILDUPLEVEL,
		
		CMD_SPR_ZHANMENGBUILDGETBUFFER,
		
		CMD_SPR_GETBAITANLOG,
		
		CMD_SPR_GETPUSHMESSAGEINFO,
		
		CMD_SPR_ACTIVATIONPICTUREJUDGE,
		
		CMD_SPR_GETNPICTUREJUDGEINFO,
		
		CMD_SPR_MUEQUIPUPGRADE,
		
		CMD_SPR_WINGUPSTAR,
		
		CMD_SPR_WINGUPGRADE,
		
		CMD_SPR_WINGOFFON,
		
		CMD_SPR_CHECK,
		
		CMD_SPR_REFERPICTUREJUDGE,
		
		CMD_SPR_GETMOJINGEXCHANGEINFO,
		
		CMD_SPR_REFRESH_ICON_STATE,
		
		CMD_SPR_EQUIPAPPENDINHERIT,
		
		CMD_SPR_SWEEP_WANMOTA,
		
		CMD_SPR_UPDATE_SWEEP_STATE,
		
		CMD_SPR_GET_WANMOTA_DETAIL,
		
		CMD_SPR_GET_SWEEP_REWARD,
		
		CMD_SPR_LISTCOPYTEAMS,
		
		CMD_SPR_COPYTEAM,
		
		CMD_SPR_COPYTEAMDATA,
		
		CMD_SPR_COPYTEAMSTATE,
		
		CMD_SPR_REGEVENTNOTIFY,
		
		CMD_SPR_LISTCOPYTEAMDATA,
		
		CMD_SPR_COPYTEAMDAMAGEINFO,
		
		CMD_SPR_GOLDCOPYSCENEPREPAREFIGHT,
		
		CMD_SPR_GOLDCOPYSCENEMONSTERWAVE,
		
		CMD_SPR_GETNEWZONEACTIVEAWARD,
		
		CMD_SPR_QUERYUPLEVELMADMAN,
		
		CMD_SPR_QUERYNEWZONEACTIVE,
		
		CMD_SPR_QUERYUPLEVELGIFTINFO,
		
		CMD_SPR_GETUPLEVELGIFTAWARD,
		
		CMD_SPR_JINGJI_START_FIGHT,
		
		CMD_SPR_QUERY_REPAYACTIVEINFO,
		
		CMD_SPR_GET_REPAYACTIVEAWARD,
		
		CMD_SPR_QUERY_ALLREPAYACTIVEINFO,
		
		CMD_SPR_QUERYACTIVITYSOMEINFO,
		
		CMD_SPR_PLAYBOSSANIMATION,
		
		CMD_SPR_ENDBOSSANIMATION,
		
		CMD_SPR_QUERY_TODAYCANDOINFO,
		
		CMD_SPR_QUERY_GETOLDRESINFO,
		
		CMD_SPR_GET_OLDRESOURCE,
		
		CMD_SPR_EXTENSIONPROPSHITED,
		
		CMD_SPR_EXEC_WASHPROPS,
		
		CMD_SPR_EXEC_WASHPROPSINHERIT,
		
		CMD_SPR_BATTLE_SCORE_LIST,
		
		CMD_SPR_STORYCOPYMAPINFO,
		
		CMD_SPR_GETUSERMAILCOUNT,
		
		CMD_SPR_QUERYIMPETRATEINFO,
		
		CMD_SPR_EXECUTEIMPETRATE,
		
		CMD_SPR_OPENMARKET2,
		
		CMD_SPR_MARKETSALEMONEY2,
		
		CMD_SPR_SALEGOODS2,
		
		CMD_SPR_SELFSALEGOODSLIST2,
		
		CMD_SPR_OTHERSALEGOODSLIST2,
		
		CMD_SPR_MARKETROLELIST2,
		
		CMD_SPR_MARKETGOODSLIST2,
		
		CMD_SPR_MARKETBUYGOODS2,
		
		CMD_SPR_QUERYSTARCONSTELLATIONINFO,
		
		CMD_SPR_EXECUTEACTIVATIONSTARCONSTELLATION,
		
		CMD_SPR_CHANGEANGLE,
		
		CMD_SPR_UPDATESHARESTATE,
		
		CMD_SPR_GETSHAREAWARD,
		
		CMD_SPR_GETSHARESTATE,
		
		CMD_SPR_BROADSPECIALHINTTEXT,
		
		CMD_SPR_MAPAIEVENT,
		
		CMD_SPR_EXEC_LIANZHI,
		
		CMD_SPR_QUERY_LIANZHICOUNT,
		
		CMD_SPR_UPGRADE_CHENGJIU,
		
		CMD_SPR_GETFIRSTCHARGEINFO,
		
		CMD_SPR_BATCHFETCHMAILGOODS,
		
		CMD_SPR_PUSH_VERSION,
		
		CMD_SPR_NOTIFYTEAMCHGZHANLI,
		
		CMD_SPR_NOTIFYSELFCHGZHANLI,
		
		CMD_SPR_NOTIFYOTHERBUFFERDATA,
		
		CMD_SPR_NOTIFYSHOWGONGGAO,
		
		CMD_SPR_GETWINGINFO,
		
		CMD_SPR_EMOLAIXIMONSTERINFO,
		
		CMD_SPR_CAIJI_START,
		
		CMD_SPR_CAIJI_FINISH,
		
		CMD_SPR_CAIJI_LASTNUM,
		
		CMD_SPR_QUERYJIERITOTALCONSUME,
		
		CMD_SPR_EXECUTEJIERITOTALCONSUME,
		
		CMD_MAP_TELEPORT,
		
		CMD_SPR_SPECIALMACHINE,
		
		CMD_SPR_EXTRADATA,
		
		CMD_SPR_GE = 699,
		
		CMD_SPR_CHENGZHAN_JINGJIA,
		
		CMD_SPR_GET_CHENGZHAN_DAILY_AWARD,
		
		CMD_SPR_LUOLANCHENGZHAN,
		
		CMD_SPR_LUOLANCHENGZHAN_LONGTA_ROLEINFO,
		
		CMD_SPR_LUOLANCHENGZHAN_QIZHI_OWNERINFO,
		
		CMD_SPR_LUOLANCHENGZHAN_LONGTA_OWNERINFO,
		
		CMD_SPR_GET_LUOLANCHENGZHU_INFO,
		
		CMD_SPR_LUOLANCHENGZHAN_RESULT_INFO,
		
		CMD_SPR_GET_LUOLANCHENGZHAN_REQUEST_INFO_LIST,
		
		CMD_SPR_SERVERUPDATE_ZHANMENGZIJIN,
		
		CMD_SPR_MODIFY_FASHION,
		
		CMD_SPR_GETBANGHUIFUBEN,
		
		CMD_SPR_GETBANGHUIFUBENAWARD,
		
		CMD_SPR_GET_ELEMENTHRT_SLIST = 720,
		
		CMD_SPR_GET_ELEMENTHRTS_INFO,
		
		CMD_SPR_USE_ELEMENTHRT,
		
		CMD_SPR_GET_SOMEELEMENTHRTS,
		
		CMD_SPR_POWER_ELEMENTHRT,
		
		CMD_SPR_RESET_EHRTSBAG,
		
		CMD_SPR_GET_USINGELEMENTHRT_SLIST,
		
		CMD_SPR_HOLD_QINGGONGYAN = 730,
		
		CMD_SPR_GET_QINGGONGYAN,
		
		CMD_SPR_JOIN_QINGGONGYAN,
		
		CMD_SPR_IFQINGGONGYANOPEN,
		
		CMD_SPR_GETDAMONGOODSLIST = 740,
		
		CMD_SPR_GET_PET_LIST = 750,
		
		CMD_SPR_GET_PET_INFO,
		
		CMD_SPR_CALL_PET,
		
		CMD_SPR_MOVE_PET,
		
		CMD_SPR_RESET_PETBAG,
		
		CMD_SPR_FAZHEN_BOSS = 760,
		
		CMD_SPR_GET_STORE_YINLIANG,
		
		CMD_SPR_GET_STORE_MONEY,
		
		CMD_SPR_STORE_YINLIANG_CHANGE,
		
		CMD_SPR_STORE_MONEY_CHANGE,
		
		CMD_SPR_JIERIACT_STATE = 770,
		
		CMD_SPR_ACHIEVEMENT_RUNE_INFO = 780,
		
		CMD_SPR_ACHIEVEMENT_RUNE_UP,
		
		CMD_SPR_PRESTIGE_MEDAL_INFO,
		
		CMD_SPR_PRESTIGE_MEDAL_UP,
		
		CMD_SPR_ARTIFACT_UP = 791,
		
		CMD_SPR_GET_LINGYU_LIST = 800,
		
		CMD_SPR_ADVANCE_LINGYU_LEVEL,
		
		CMD_SPR_ADVANCE_LINGYU_SUIT,
		
		CMD_SPR_WING_ZHULING = 810,
		
		CMD_SPR_WING_ZHUHUN,
		
		CMD_SPR_HYSY_LIANSHA = 818,
		
		CMD_SPR_HYSY_STOP_LIANSHA,
		
		CMD_SPR_HYSY_ENQUEUE,
		
		CMD_SPR_HYSY_DEQUEUE,
		
		CMD_SPR_HYSY_QUEUE_PLAYER_NUM,
		
		CMD_SPR_HYSY_ENTER_NOTIFY,
		
		CMD_SPR_HYSY_ENTER_RESPOND,
		
		CMD_SPR_HYSY_AWARD,
		
		CMD_SPR_HYSY_SCORE_INFO,
		
		CMD_SPR_NOTIFY_TIME_STATE,
		
		CMD_SPR_HYSY_SUCCESS_COUNT,
		
		CMD_SPR_HYSY_ADD_SCORE,
		
		CMD_SPR_REGION_EVENT,
		
		CMD_SYNC_TIME_BY_CLIENT,
		
		CMD_SPR_GETLUOLANCHENGZHU = 840,
		
		CMD_SPR_QUERYADRATIONLANCHENGZHUO,
		
		CMD_SPR_ADRATIONLANCHENGZHU,
		
		CMD_SPR_GET_YUEKA_DATA = 850,
		
		CMD_SPR_GET_YUEKA_AWARD,
		
		CMD_SECOND_PASSWORD_CHECK_STATE = 860,
		
		CMD_SECOND_PASSWORD_SET,
		
		CMD_SECOND_PASSWORD_VERIFY,
		
		CMD_SECOND_PASSWORD_CANCEL,
		
		CMD_SPR_MARRY_FUBEN = 870,
		
		CMD_SPR_MARRY_ROSE,
		
		CMD_SPR_MARRY_RING,
		
		CMD_SPR_MARRY_MESSAGE,
		
		CMD_SPR_MARRY_PARTY_QUERY = 880,
		
		CMD_SPR_MARRY_PARTY_CREATE,
		
		CMD_SPR_MARRY_PARTY_CANCEL,
		
		CMD_SPR_MARRY_PARTY_JOIN,
		
		CMD_SPR_MARRY_PARTY_JOIN_LIST,
		
		CMD_SPR_MARRY_INIT = 890,
		
		CMD_SPR_MARRY_REPLY,
		
		CMD_SPR_MARRY_DIVORCE,
		
		CMD_SPR_MARRY_AUTO_REJECT,
		
		CMD_SPR_MARRY_NOTIFY,
		
		CMD_SPR_MARRY_UPDATE,
		
		CMD_SPR_MARRY_SPOUSE_DATA,
		
		CMD_SPR_RETURN_RECELL_INFO = 900,
		
		CMD_SPR_RETURN_RECELL_SET,
		
		CMD_SPR_RETURN_AWARD_INFO,
		
		CMD_SPR_RETURN_AWARD_SET,
		
		CMD_SPR_RETURN_CHECK_INFO,
		
		CMD_SPR_RETURN_CHECK_SET,
		
		CMD_SPR_RETURN_RECELL_AWARD_INFO,
		
		CMD_SPR_RETURN_RECELL_AWARD_SET,
		
		CMD_SPR_RETURN_RECELL_EXTRA_AWARD,
		
		CMD_SPR_QUERY_JIERI_GIVE_INFO = 920,
		
		CMD_SPR_JIERI_GIVE_TO_OTHER,
		
		CMD_SPR_GET_JIERI_GIVE_AWARD,
		
		CMD_SPR_QUERY_JIERI_GIVE_KING_INFO,
		
		CMD_SPR_GET_JIERI_GIVE_KING_AWARD,
		
		CMD_SPR_QUERY_JIERI_RECV_KING_INFO,
		
		CMD_SPR_GET_JIERI_RECV_KING_AWARD,
		
		CMD_DB_EXECUXJIERIFANLI,
		
		CMD_SPR_QUERY_GUARD_POINT_RECOVER = 930,
		
		CMD_SPR_GUARD_POINT_RECOVER,
		
		CMD_SPR_QUERY_GUARD_STATUE_INFO,
		
		CMD_SPR_GUARD_STATUE_LEVEL_UP,
		
		CMD_SPR_GUARD_STATUE_SUIT_UP,
		
		CMD_SPR_MOD_GUARD_SOUL_EQUIP,
		
		CMD_SPR_QUERY_LIANXU_CHARGE_INFO = 940,
		
		CMD_SPR_GET_LIANXU_CHARGE_AWARD,
		
		CMD_SPR_QUERY_JIERI_RECV_INFO = 944,
		
		CMD_SPR_GET_JIERI_RECV_AWARD,
		
		CMD_SPR_TIANTI_JOIN = 950,
		
		CMD_SPR_TIANTI_QUIT,
		
		CMD_SPR_TIANTI_ENTER,
		
		CMD_SPR_TIANTI_AWARD,
		
		CMD_SPR_TIANTI_DAY_DATA,
		
		CMD_SPR_TIANTI_MONTH_PAIHANG,
		
		CMD_SPR_TIANTI_GET_PAIMING_AWARDS,
		
		CMD_SPR_ROLE_ATTRIBUTE_VALUE = 968,
		
		CMD_SPR_TIANTI_GET_LOG,
		
		CMD_SPR_TALENT_GET_DATA = 1000,
		
		CMD_SPR_TALENT_ADD_EXP,
		
		CMD_SPR_TALENT_WASH,
		
		CMD_SPR_TALENT_ADD_EFFECT,
		
		CMD_SPR_HOLYITEM_DATA,
		
		CMD_SPR_HOLYITEM_PART_DATA,
		
		CMD_DB_START_CMD = 10000,
		
		CMD_DB_UPDATE_POS,
		
		CMD_DB_UPDATE_EXPLEVEL,
		
		CMD_DB_UPDATE_INTERPOWER,
		
		CMD_DB_UPDATEMONEY1_CMD,
		
		CMD_DB_ADDGOODS_CMD,
		
		CMD_DB_UPDATEGOODS_CMD,
		
		CMD_DB_UPDATETASK_CMD,
		
		CMD_DB_UPDATEPKMODE_CMD,
		
		CMD_DB_UPDATEPKVAL_CMD,
		
		CMD_DB_UPDATEKEYS,
		
		CMD_DB_UPDATEUSERMONEY_CMD,
		
		CMD_DB_UPDATEUSERYINLIANG_CMD,
		
		CMD_DB_MOVEGOODS_CMD,
		
		CMD_DB_UPDATE_LEFTFIGHTSECS,
		
		CMD_DB_ROLE_ONLINE,
		
		CMD_DB_ROLE_HEART,
		
		CMD_DB_ROLE_OFFLINE,
		
		CMD_DB_GET_CHATMSGLIST,
		
		CMD_DB_HORSEON,
		
		CMD_DB_HORSEOFF,
		
		CMD_DB_PETOUT,
		
		CMD_DB_PETIN,
		
		CMD_DB_ADDDJPOINT,
		
		CMD_DB_UPJINGMAI_LEVEL,
		
		CMD_DB_REGUSERID,
		
		CMD_DB_BANROLENAME,
		
		CMD_DB_BANROLECHAT,
		
		CMD_DB_GETBANROLECATDICT,
		
		CMD_DB_ADDBULLMSG,
		
		CMD_DB_REMOVEBULLMSG,
		
		CMD_DB_GETBULLMSGDICT,
		
		CMD_DB_UPDATEONLINETIME,
		
		CMD_DB_GAMECONFIGDICT,
		
		CMD_DB_GAMECONIFGITEM,
		
		CMD_DB_RESETBIGUAN,
		
		CMD_DB_ADDSKILL,
		
		CMD_DB_UPSKILLINFO,
		
		CMD_DB_UPDATEJINGMAIEXP,
		
		CMD_DB_UPDATEDEFSKILLID,
		
		CMD_DB_UPDATEAUTODRINK,
		
		CMD_DB_UPDATEDAILYTASKDATA,
		
		CMD_DB_UPDATEDAILYJINGMAI,
		
		CMD_DB_UPDATENUMSKILLID,
		
		CMD_DB_UPDATEPBINFO,
		
		CMD_DB_UPDATHUODONGINFO,
		
		CMD_DB_SUBCHONGZHIJIFEN,
		
		CMD_DB_USELIPINMA,
		
		CMD_DB_UPDATEFUBENDATA,
		
		CMD_DB_GETFUBENSEQID,
		
		CMD_DB_UPDATEROLEDAILYDATA,
		
		CMD_DB_UPDATEBUFFERITEM,
		
		CMD_DB_UNDELROLENAME,
		
		CMD_DB_ADDFUBENHISTDATA,
		
		CMD_DB_UPDATELIANZHAN,
		
		CMD_DB_UPDATEKILLBOSS,
		
		CMD_DB_UPDATEROLESTAT,
		
		CMD_DB_UPDATEYABIAODATA,
		
		CMD_DB_UPDATEYABIAODATASTATE,
		
		CMD_DB_UPDATEBATTLENAME,
		
		CMD_DB_ADDMALLBUYITEM,
		
		CMD_DB_GETLIPINMAINFO,
		
		CMD_DB_UPDATECZTASKID,
		
		CMD_DB_GETTOTALONLINENUM,
		
		CMD_DB_UPDATEBATTLENUM,
		
		CMD_DB_UPDATEHEROINDEX,
		
		CMD_DB_FORCERELOADPAIHANG,
		
		CMD_DB_ADDYINPIAOBUYITEM,
		
		CMD_DB_DELROLENAME,
		
		CMD_SPR_QUERYUMBYNAME,
		
		CMD_DB_QUERYBHMGRLIST,
		
		CMD_DB_UPDATEBANGGONG_CMD,
		
		CMD_DB_UPDATEBHTONGQIAN_CMD,
		
		CMD_DB_GETBHJUNQILIST,
		
		CMD_DB_GETBHLINGDIDICT,
		
		CMD_DB_UPDATELINGDIFORBH,
		
		CMD_DB_GETLEADERROLEIDBYBHID,
		
		CMD_DB_ADDBHTONGQIAN_CMD,
		
		CMD_DB_ADDQIZHENGEBUYITEM,
		
		CMD_DB_UPDATEJIEBIAOINFO,
		
		CMD_DB_ADDREFRESHQIZHENREC,
		
		CMD_DB_CLEARCACHINGROLEIDATA,
		
		CMD_DB_ADDMONEYWARNING,
		
		CMD_DB_QUERYCHONGZHIMONEY,
		
		CMD_DB_ADDYINLIANGBUYITEM,
		
		CMD_DB_ADDBANGGONGBUYITEM,
		
		CMD_DB_SENDUSERMAIL,
		
		CMD_DB_GETUSERMAILDATA,
		
		CMD_DB_FINDROLEID_BYROLENAME,
		
		CMD_DB_QUERYLIMITGOODSUSEDNUM,
		
		CMD_DB_UPDATELIMITGOODSUSEDNUM,
		
		CMD_DB_UPDATEDAILYVIPDATA,
		
		CMD_DB_UPDATEDAILYYANGGONGBKJIFENDATA,
		
		CMD_DB_UPDATESINGLETIMEAWARDFLAG,
		
		CMD_DB_ADDSHENGXIAOGUESSHIST,
		
		CMD_DB_UPDATEUSERGOLD_CMD,
		
		CMD_DB_ADDGOLDBUYITEM,
		
		CMD_DB_UPDATEROLEBAGNUM,
		
		CMD_DB_SETLINGDIWARREQUEST,
		
		CMD_DB_UPDATEGOODSLIMIT,
		
		CMD_DB_UPDATEROLEPARAM,
		
		CMD_DB_ADDQIANGGOUBUYITEM,
		
		CMD_DB_ADDQIANGGOUITEM,
		
		CMD_DB_QUERYCURRENTQIANGGOUITEM,
		
		CMD_DB_QUERYQIANGGOUBUYITEMS,
		
		CMD_DB_UPDATEQIANGGOUTIMEOVER,
		
		CMD_DB_GETBANGHUIMINIDATA,
		
		CMD_DB_ADDBUYITEMFROMNPC,
		
		CMD_DB_ADDZAJINDANHISTORY,
		
		CMD_DB_QUERYQIANGGOUBUYITEMINFO,
		
		CMD_DB_QUERYFIRSTCHONGZHIBYUSERID,
		
		CMD_DB_QUERYKAIFUONLINEAWARDROLEID,
		
		CMD_DB_ADDKAIFUONLINEAWARD,
		
		CMD_DB_ADDGIVEUSERMONEYITEM,
		
		CMD_DB_QUERYKAIFUONLINEAWARDLIST,
		
		CMD_DB_ADDEXCHANGE1ITEM,
		
		CMD_DB_ADDEXCHANGE2ITEM,
		
		CMD_DB_ADDEXCHANGE3ITEM,
		
		CMD_DB_ADDFALLGOODSITEM,
		
		CMD_DB_UPDATEROLEPROPS,
		
		CMD_DB_QUERYTODAYCHONGZHIMONEY,
		
		CMD_DB_QUERYDAYCHONGZHIBYUSERID,
		
		CMD_DB_CLEARALLCACHINGROLEDATA,
		
		CMD_DB_QUERYXINGYUNORYUEDUCHOUJIANGINFO,
		
		CMD_DB_EXECUXINGYUNORYUEDUCHOUJIANGINFO,
		
		CMD_DB_ADDYUEDUCHOUJIANGHISTORY,
		
		CMD_DB_EXECUTECHANGEOCCUPATION,
		
		CMD_DB_QUERYBLOODCASTLEENTERCOUNT,
		
		CMD_DB_UPDATEBLOODCASTLEENTERCOUNT,
		
		CMD_DB_QUERYFUBENHISINFO,
		
		CMD_DB_CLEANDATAWHENFRESHPLAYERLOGOUT,
		
		CMD_DB_FINISHFRESHPLAYERSTATUS,
		
		CMD_DB_EXECUTECHANGETASKSTARLEVEL,
		
		CMD_DB_EXECUTEUPDATEROLESOMEINFO,
		
		CMD_DB_QUERYDAYACTIVITYTOTALPOINT,
		
		CMD_DB_QUERYDAYACTIVITYSELFPOINT,
		
		CMD_DB_UPDATEDAYACTIVITYSELFPOINT,
		
		CMD_DB_QUERYEVERYDAYONLINEAWARDGIFTINFO,
		
		CMD_DB_ADD_ZHANMENGSHIJIAN,
		
		CMD_DB_ZHANMENGSHIJIAN_DETAIL,
		
		CMD_DB_JINGJICHANG_GET_DATA,
		
		CMD_DB_JINGJICHANG_GET_CHALLENGE_DATA,
		
		CMD_DB_JINGJICHANG_CREATE_DATA,
		
		CMD_DB_JINGJICHANG_REQUEST_CHALLENGE,
		
		CMD_DB_JINGJICHANG_CHALLENGE_END,
		
		CMD_DB_JINGJICHANG_SAVE_DATA,
		
		CMD_DB_JINGJICHANG_ZHANBAO_DATA,
		
		CMD_DB_JINGJICHANG_REMOVE_CD,
		
		CMD_DB_JINGJICHANG_GET_RANKING_AND_NEXTREWARDTIME,
		
		CMD_DB_JINGJICHANG_UPDATE_NEXTREWARDTIME,
		
		CMD_DB_ADD_BAITANLOG,
		
		CMD_DB_UPDATEPUSHMESSAGEINFO,
		
		CMD_DB_QUERYPUSHMESSAGEUSERLIST,
		
		CMD_DB_ADDWING,
		
		CMD_DB_MODWING,
		
		CMD_DB_REFERPICTUREJUDGE,
		
		CMD_DB_QUERYMOJINGEXCHANGEINFO,
		
		CMD_DB_UPDATEMOJINGEXCHANGEINFO,
		
		CMD_DB_MODIFY_WANMOTA,
		
		CMD_DB_GET_WANMOTA_DETAIL,
		
		CMD_DB_QUERY_REPAYACTIVEINFO,
		
		CMD_DB_GET_REPAYACTIVEAWARD,
		
		CMD_DB_UPDATE_ACCOUNT_ACTIVE,
		
		CMD_DB_QUERY_GETOLDRESINFO,
		
		CMD_DB_UPDATE_OLDRESOURCE,
		
		CMD_DB_UPDATEGOODS_CMD2,
		
		CMD_DB_UPDATESTARCONSTELLATION,
		
		CMD_DB_SAVECONSUMELOG,
		
		CMD_DB_QUERYVIPLEVELAWARDFLAG,
		
		CMD_DB_UPDATEVIPLEVELAWARDFLAG,
		
		CMD_DB_UPDATEFIRSTCHARGE,
		
		CMD_DB_FIRSTCHARGE_CONFIG,
		
		CMD_DB_UPDATEBANGHUIFUBEN,
		
		CMD_DB_ADD_STORE_YINLIANG,
		
		CMD_DB_ADD_STORE_MONEY,
		
		CMD_DB_GM_UPDATE_BANGLEVEL,
		
		CMD_DB_UPDATE_LINGYU,
		
		CMD_DB_REQUESTNEWGMAILLIST,
		
		CMD_DB_MODIFYROLEGMAIL,
		
		CMD_DB_QUERYROLEMONEYINFO,
		
		CMD_DB_ALL_COMPLETION_OF_TASK_BY_TASKID,
		
		CMD_DB_ROLE_BUY_YUE_KA_BUT_OFFLINE,
		
		CMD_DB_MODIFY_ROLE_HUO_BI_OFFLINE,
		
		CMD_DB_UPDATE_USR_SECOND_PASSWORD,
		
		CMD_DB_GET_USR_SECOND_PASSWORD,
		
		CMD_DB_UPDATE_MARRY_DATA,
		
		CMD_DB_GET_MARRY_DATA,
		
		CMD_DB_MARRY_PARTY_QUERY,
		
		CMD_DB_MARRY_PARTY_ADD,
		
		CMD_DB_MARRY_PARTY_REMOVE,
		
		CMD_DB_MARRY_PARTY_JOIN_INC,
		
		CMD_DB_MARRY_PARTY_JOIN_CLEAR,
		
		CMD_DB_TIANTI_ADD_ZHANBAO_LOG = 10200,
		
		CMD_DB_TIANTI_UPDATE_ROLE_DATA,
		
		CMD_DB_TIANTI_UPDATE_RONGYAO,
		
		CMD_DB_MERLIN_CREATE,
		
		CMD_DB_MERLIN_UPDATE,
		
		CMD_DB_MERLIN_QUERY,
		
		CMD_DB_UPDATE_HOLYITEM,
		
		CMD_DB_GET_SERVERLIST = 11000,
		
		CMD_DB_ONLINE_SERVERHEART,
		
		CMD_LOGDB_ADD_ITEM_LOG = 20000,
		
		CMD_LOGDB_ADD_TRADEMONEY_FREQ_LOG,
		
		CMD_LOGDB_ADD_TRADEMONEY_NUM_LOG,
		
		CMD_DB_ERR_RETURN = 32767
	}
}
